In [21]:
import yaml
import os
import polars as pl
from datetime import datetime 
from functools import partial
with open("../config/config.yaml", "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

data_dir = config["data_dir"]
print(data_dir  )
if os.path.exists(data_dir) and os.path.isdir(data_dir):
    list_of_files = os.listdir(data_dir)
else:
    list_of_files = []
print(list_of_files)

E:\smallcaps_data
['AIXI.parquet', 'APUS.parquet', 'BAOS.parquet', 'BEAT.parquet', 'BIAF.parquet', 'CAN.parquet', 'CDTG.parquet', 'CHAI.parquet', 'CHPT.parquet', 'CISS.parquet', 'COOT.parquet', 'CYAB.parquet', 'FBGL.parquet', 'FLYE.parquet', 'GCDT.parquet', 'GIPR.parquet', 'GRI.parquet', 'GRML.parquet', 'IMCC.parquet', 'IMRN.parquet', 'LIDR.parquet', 'logs', 'MEDS.parquet', 'MMA.parquet', 'NCPL.parquet', 'NCRA.parquet', 'NEOV.parquet', 'NMRA.parquet', 'OFAL.parquet', 'OLB.parquet', 'OLOX.parquet', 'output', 'PDSB.parquet', 'PFSA.parquet', 'SBFM.parquet', 'SDEV.parquet', 'SGRX.parquet', 'SKYA.parquet', 'SKYQ.parquet', 'SLND.parquet', 'SOAR.parquet', 'SPHL.parquet', 'STAK.parquet', 'TCRT.parquet', 'TNMG.parquet', 'TOPP.parquet', 'TRUG.parquet', 'USDE.parquet', 'VEEA.parquet', 'VRA.parquet', 'VRME.parquet', 'XHLD.parquet', 'XLAB.parquet', 'XPON.parquet', 'XTNT.parquet', '_catalog.parquet']

In [22]:
list_of_files = [f for f in list_of_files if f.endswith(".parquet")]
from datetime import date

tickers_days = {
    "TCRT": ["2026-10-13"],
    "VEEA": ["2026-10-09", "2026-10-05"],
}

columns = ["datetime", "ticker", "open", "high", "low", "close", "volume"]
frames = []

for ticker, days in tickers_days.items():
    parquet_path = os.path.join(data_dir, f"{ticker}.parquet")

    if not os.path.isfile(parquet_path):
        raise FileNotFoundError(f"No existe el paquete Parquet para {ticker}: {parquet_path}")

    requested_days = [date.fromisoformat(day) for day in days]

    ticker_df = (
        pl.read_parquet(parquet_path)
        .filter(pl.col("datetime").dt.date().is_in(requested_days))
        .with_columns(pl.lit(ticker).alias("ticker"))
        .select(columns)
    )

    frames.append(ticker_df)

df = pl.concat(frames).sort(["ticker", "datetime"])
df

shape: (2_704, 7)
┌─────────────────────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ datetime                ┆ ticker ┆ open   ┆ high   ┆ low    ┆ close  ┆ volume │
│ ---                     ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs, UTC]       ┆ str    ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 2026-10-13 08:00:00 UTC ┆ TCRT   ┆ 1.0    ┆ 1.01   ┆ 0.9897 ┆ 0.9897 ┆ 2177   │
│ 2026-10-13 08:03:00 UTC ┆ TCRT   ┆ 0.9905 ┆ 1.02   ┆ 0.9896 ┆ 0.9896 ┆ 7586   │
│ 2026-10-13 08:04:00 UTC ┆ TCRT   ┆ 0.9896 ┆ 1.0    ┆ 0.9896 ┆ 1.0    ┆ 472    │
│ 2026-10-13 08:09:00 UTC ┆ TCRT   ┆ 1.03   ┆ 1.05   ┆ 1.03   ┆ 1.05   ┆ 1357   │
│ 2026-10-13 08:14:00 UTC ┆ TCRT   ┆ 1.0499 ┆ 1.0499 ┆ 1.0499 ┆ 1.0499 ┆ 363    │
│ …                       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2026-10-09 23:55:00 UTC ┆ VEEA   ┆ 5.04   ┆ 5.05   ┆ 4.99   ┆ 4.99   ┆ 5726   │
│ 2026-10-09 23:56:00 UTC ┆ VEEA   ┆ 4.98   ┆ 4.98   ┆ 4.95   ┆ 4.95   ┆ 4462   │
│ 2026-10-09 23:57:00 UTC ┆ VEEA   ┆ 4.98   ┆ 4.98   ┆ 4.9715 ┆ 4.98   ┆ 1456   │
│ 2026-10-09 23:58:00 UTC ┆ VEEA   ┆ 5.0    ┆ 5.01   ┆ 4.99   ┆ 4.99   ┆ 5081   │
│ 2026-10-09 23:59:00 UTC ┆ VEEA   ┆ 4.9901 ┆ 5.01   ┆ 4.98   ┆ 5.01   ┆ 5599   │
└─────────────────────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [23]:
GROUPS = ["ticker", "trading_day"]


def daily_vwap():
    return [
        (
            (pl.col("price") * pl.col("volume")).cum_sum().over(GROUPS)
            / pl.col("volume").cum_sum().over(GROUPS)
        ).alias("vwap_daily")
    ]


def atr(period=14):
    previous_close = pl.col("close").shift(1).over(GROUPS)

    true_range = pl.max_horizontal(
        pl.col("high") - pl.col("low"),
        (pl.col("high") - previous_close).abs(),
        (pl.col("low") - previous_close).abs(),
    )

    return [
        true_range
        .rolling_mean(window_size=period, min_samples=period)
        .over(GROUPS)
        .alias(f"atr_{period}")
    ]


def rsi(period=14):
    change = pl.col("close").diff().over(GROUPS)
    gain = pl.when(change > 0).then(change).otherwise(0.0)
    loss = pl.when(change < 0).then(-change).otherwise(0.0)

    average_gain = (
        gain.ewm_mean(alpha=1 / period, adjust=False, min_samples=period)
        .over(GROUPS)
    )
    average_loss = (
        loss.ewm_mean(alpha=1 / period, adjust=False, min_samples=period)
        .over(GROUPS)
    )

    return [
        pl.when(average_loss == 0)
        .then(100.0)
        .when(average_gain == 0)
        .then(0.0)
        .otherwise(100.0 - (100.0 / (1.0 + average_gain / average_loss)))
        .alias(f"rsi_{period}")
    ]


def donchian_channels(period=20):
    upper = pl.col("high").rolling_max(period, min_samples=period).over(GROUPS)
    lower = pl.col("low").rolling_min(period, min_samples=period).over(GROUPS)

    return [
        upper.alias(f"donchian_upper_{period}"),
        lower.alias(f"donchian_lower_{period}"),
        ((upper + lower) / 2).alias(f"donchian_middle_{period}"),
    ]


def momentum(period=10):
    return [
        (
            pl.col("close")
            - pl.col("close").shift(period).over(GROUPS)
        ).alias(f"momentum_{period}")
    ]

def mean_vol(period=100):
    mean_vol = pl.col('volume').rolling_mean(period,min_samples=period).over(GROUPS)
    return [
        mean_vol.alias(f"mean_vol_{period}")
    ]

def median_vol(period=100):
    mean_vol = pl.col('volume').rolling_median(period,min_samples=period).over(GROUPS)
    return [
        mean_vol.alias(f"median_vol_{period}")
    ]

def ema(period: int = 100):
    return [
        pl.col("close")
        .ewm_mean(span=period, adjust=False, min_samples=period)
        .over(GROUPS)
        .alias(f"ema_{period}")
    ]
def vortex(period: int = 14):
    previous_close = pl.col("close").shift(1).over(GROUPS)
    previous_high = pl.col("high").shift(1).over(GROUPS)
    previous_low = pl.col("low").shift(1).over(GROUPS)

    true_range = pl.max_horizontal(
        pl.col("high") - pl.col("low"),
        (pl.col("high") - previous_close).abs(),
        (pl.col("low") - previous_close).abs(),
    )

    positive_movement = (pl.col("high") - previous_low).abs()
    negative_movement = (pl.col("low") - previous_high).abs()

    true_range_sum = true_range.rolling_sum(period, min_samples=period).over(GROUPS)

    return [
        (
            positive_movement.rolling_sum(period, min_samples=period).over(GROUPS)
            / true_range_sum
        ).alias(f"vortex_plus_{period}"),
        (
            negative_movement.rolling_sum(period, min_samples=period).over(GROUPS)
            / true_range_sum
        ).alias(f"vortex_minus_{period}"),
    ]
def acceleration(period=5, smooth=3, lag=1):
    """Calcula velocidad porcentual suavizada y cambio de velocidad."""
    for name, value in (("period", period), ("smooth", smooth), ("lag", lag)):
        if isinstance(value, bool) or not isinstance(value, int) or value < 1:
            raise ValueError(f"{name} debe ser un entero positivo")

    previous_close = pl.col("close").shift(period)

    velocity = (
        pl.when(previous_close > 0)
        .then(100.0 * (pl.col("close") / previous_close - 1.0))
        .otherwise(None)
        .ewm_mean(
            span=smooth,
            adjust=False,
            min_samples=smooth,
            ignore_nulls=True,
        )
    )

    return [
        velocity.over(GROUPS).alias(f"velocity_{period}_{smooth}"),
        (velocity - velocity.shift(lag))
        .over(GROUPS)
        .alias(f"acceleration_{period}_{smooth}_{lag}"),
    ]
def williams_r(period=14):
    """Posición del cierre dentro del rango reciente, entre -100 y 0."""
    if isinstance(period, bool) or not isinstance(period, int) or period < 1:
        raise ValueError("period debe ser un entero positivo")

    highest = pl.col("high").rolling_max(period, min_samples=period)
    lowest = pl.col("low").rolling_min(period, min_samples=period)
    price_range = highest - lowest

    return [
        pl.when(price_range > 0)
        .then(-100.0 * (highest - pl.col("close")) / price_range)
        .otherwise(None)
        .over(GROUPS)
        .alias(f"williams_r_{period}")
    ]
def bollinger_bands(
    period=20,
    upper_std=2.0,
    lower_std=2.0,
    ma_type="sma",
):
    """Bandas con media SMA/EMA y multiplicadores independientes."""
    import math

    if isinstance(period, bool) or not isinstance(period, int) or period < 1:
        raise ValueError("period debe ser un entero positivo")

    ma_type = ma_type.lower()
    if ma_type not in ("sma", "ema"):
        raise ValueError("ma_type debe ser 'sma' o 'ema'")

    for name, value in (("upper_std", upper_std), ("lower_std", lower_std)):
        if (
            isinstance(value, bool)
            or not isinstance(value, (int, float))
            or not math.isfinite(value)
            or value < 0
        ):
            raise ValueError(f"{name} debe ser un número finito no negativo")

    close = pl.col("close")

    if ma_type == "sma":
        middle = close.rolling_mean(period, min_samples=period)
    else:
        middle = close.ewm_mean(
            span=period,
            adjust=False,
            min_samples=period,
        )

    deviation = close.rolling_std(
        period,
        min_samples=period,
        ddof=0,
    )

    return [
        middle.over(GROUPS).alias(f"bb_middle_{period}"),
        (middle + deviation * upper_std)
        .over(GROUPS)
        .alias(f"bb_upper_{period}"),
        (middle - deviation * lower_std)
        .over(GROUPS)
        .alias(f"bb_lower_{period}"),
    ]
def roc(period=10):
    """Variación porcentual del cierre respecto a n barras atrás."""
    if isinstance(period, bool) or not isinstance(period, int) or period < 1:
        raise ValueError("period debe ser un entero positivo")

    previous_close = pl.col("close").shift(period)

    return [
        pl.when(previous_close > 0)
        .then(100.0 * (pl.col("close") / previous_close - 1.0))
        .otherwise(None)
        .over(GROUPS)
        .alias(f"roc_{period}")
    ]
def add_indicators(frame, indicator_functions):
    expressions = [
        expression
        for indicator_function in indicator_functions
        for expression in indicator_function()
    ]
    return frame.with_columns(expressions)


df_to_plot = (
    df
    .with_columns(
        pl.col("datetime").dt.convert_time_zone("America/New_York").alias("datetime")
    )
    .sort(["ticker", "datetime"])
    .with_columns(
        pl.col("datetime").dt.date().alias("trading_day"),
        ((pl.col("high") + pl.col("low") + pl.col("close")) / 3).alias("price"),
    )
)

df_to_plot = add_indicators(
    df_to_plot,
    [
        daily_vwap,
        atr,
        # bollinger_bands,
        # partial(bollinger_bands,50,2),
        rsi,
        # partial(rsi, period=3),  # RSI de 3 períodos
        partial(donchian_channels,20),
        momentum,
        partial(mean_vol,100),
        # median_vol,
        partial(ema, 50),
        # partial(ema, 10),
        # partial(acceleration, period=5, smooth=3, lag=1),
        # vortex,
        # partial(williams_r, period=14),
        partial(roc, period=10),
        partial(bollinger_bands,period=50,ma_type="ema",upper_std=2.0,lower_std=2.0,),
    ],
)

df_to_plot

shape: (2_704, 22)
┌─────────────┬────────┬────────┬────────┬───┬───────────┬─────────────┬─────────────┬─────────────┐
│ datetime    ┆ ticker ┆ open   ┆ high   ┆ … ┆ roc_10    ┆ bb_middle_5 ┆ bb_upper_50 ┆ bb_lower_50 │
│ ---         ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---       ┆ 0           ┆ ---         ┆ ---         │
│ datetime[μs ┆ str    ┆ f64    ┆ f64    ┆   ┆ f64       ┆ ---         ┆ f64         ┆ f64         │
│ , America/N ┆        ┆        ┆        ┆   ┆           ┆ f64         ┆             ┆             │
│ ew_York]    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
╞═════════════╪════════╪════════╪════════╪═══╪═══════════╪═════════════╪═════════════╪═════════════╡
│ 2026-10-13  ┆ TCRT   ┆ 1.0    ┆ 1.01   ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:00:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-13  ┆ TCRT   ┆ 0.9905 ┆ 1.02   ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:03:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-13  ┆ TCRT   ┆ 0.9896 ┆ 1.0    ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:04:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-13  ┆ TCRT   ┆ 1.03   ┆ 1.05   ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:09:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-13  ┆ TCRT   ┆ 1.0499 ┆ 1.0499 ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:14:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ …           ┆ …      ┆ …      ┆ …      ┆ … ┆ …         ┆ …           ┆ …           ┆ …           │
│ 2026-10-09  ┆ VEEA   ┆ 5.04   ┆ 5.05   ┆ … ┆ 0.714488  ┆ 4.914584    ┆ 5.080254    ┆ 4.748915    │
│ 19:55:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-09  ┆ VEEA   ┆ 4.98   ┆ 4.98   ┆ … ┆ -1.0      ┆ 4.915973    ┆ 5.08031     ┆ 4.751636    │
│ 19:56:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-09  ┆ VEEA   ┆ 4.98   ┆ 4.98   ┆ … ┆ 0.201207  ┆ 4.918484    ┆ 5.08357     ┆ 4.753398    │
│ 19:57:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-09  ┆ VEEA   ┆ 5.0    ┆ 5.01   ┆ … ┆ -0.795229 ┆ 4.921288    ┆ 5.086917    ┆ 4.75566     │
│ 19:58:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-09  ┆ VEEA   ┆ 4.9901 ┆ 5.01   ┆ … ┆ 1.829268  ┆ 4.924767    ┆ 5.093134    ┆ 4.756401    │
│ 19:59:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
└─────────────┴────────┴────────┴────────┴───┴───────────┴─────────────┴─────────────┴─────────────┘

In [25]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from IPython.display import HTML, display


GROUPS = ["ticker", "trading_day"]

plot_df = (
    df_to_plot
    .sort(["ticker", "datetime"])
    .with_row_index("plot_x")
)


def add_segmented_line(fig, frame, column, name, row, color, dash="solid", width=1):
    """Añade una línea sin conectar distintos tickers ni días."""
    show_legend = True

    for segment in frame.partition_by(GROUPS, maintain_order=True):
        valid_segment = segment.drop_nulls(column)

        if valid_segment.height == 0:
            continue

        fig.add_trace(
            go.Scatter(
                x=valid_segment["plot_x"].to_list(),
                y=valid_segment[column].to_list(),
                mode="lines",
                name=name,
                legendgroup=name,
                showlegend=show_legend,
                line={"color": color, "dash": dash, "width": width},
            ),
            row=row,
            col=1,
        )

        show_legend = False


volume_colors = [
    "green" if close > open_price
    else "red" if close < open_price
    else "gray"
    for open_price, close in zip(
        plot_df["open"].to_list(),
        plot_df["close"].to_list(),
    )
]

fig = make_subplots(
    rows=5,
    cols=1,
    shared_xaxes=True,
    vertical_spacing=0.025,
    row_heights=[0.50, 0.15, 0.12, 0.12, 0.11],
    subplot_titles=(
        "Precio, VWAP, Bollinger y Donchian",
        "Volumen",
        "RSI",
        "ATR",
        "ROC",
    ),
)

fig.add_trace(
    go.Candlestick(
        x=plot_df["plot_x"].to_list(),
        open=plot_df["open"].to_list(),
        high=plot_df["high"].to_list(),
        low=plot_df["low"].to_list(),
        close=plot_df["close"].to_list(),
        name="Precio",
    ),
    row=1,
    col=1,
)

# Precio
add_segmented_line(fig, plot_df, "vwap_daily", "VWAP", 1,  "#1030e7", width=2)

# Bandas de Bollinger
# add_segmented_line(fig, plot_df, "bb_upper_50", "BB superior", 1, "#7f7f7f", "dot")
# add_segmented_line(fig, plot_df, "bb_middle_50", "BB media", 1, "#7f7f7f")
# add_segmented_line(fig, plot_df, "bb_lower_50", "BB inferior", 1, "#7f7f7f", "dot")

# Canales de Donchian
add_segmented_line(
    fig, plot_df, "donchian_upper_20", "Donchian superior", 1, "#9467bd", "dash"
)
add_segmented_line(
    fig, plot_df, "donchian_middle_20", "Donchian medio", 1, "#9467bd", "dot"
)
add_segmented_line(
    fig, plot_df, "donchian_lower_20", "Donchian inferior", 1, "#9467bd", "dash"
)
add_segmented_line(
    fig, plot_df, "ema_50", "ema 50", 1, "#1dc0dd", "solid"
)
# add_segmented_line(
#     fig, plot_df, "ema_10", "ema 10", 1, "#ca4095", "solid"
# )

# Volumen: vela alcista rojo, vela bajista verde
fig.add_trace(
    go.Bar(
        x=plot_df["plot_x"].to_list(),
        y=plot_df["volume"].to_list(),
        marker_color=volume_colors,
        name="Volumen",
    ),
    row=2,
    col=1,
)
#agrego la linea de media y mediana volumen
# add_segmented_line(fig, plot_df, "mean_vol_100", "mean_vol_100", 2, "#922909", width=2)
# add_segmented_line(fig, plot_df, "median_vol_100", "median_vol_100", 2, "#b89112", width=2)



# Indicadores inferiores
add_segmented_line(fig, plot_df, "atr_14", "ATR 14", 4, "#1f77b4", width=2)
add_segmented_line(fig, plot_df, "rsi_14", "RSI 14", 3, "#ff7f0e", width=2)
add_segmented_line(fig, plot_df, "roc_10", "ROC 10", 5, "#690d40", width=2)
# add_segmented_line(fig, plot_df, "velocity_5_3", "velocity_5_3", 4, "#2ca02c", width=2)
# add_segmented_line(fig, plot_df, "williams_r_14", "williams_r_14", 4, "#2ca02c", width=2)
# fig.update_yaxes(range=[0, -100], row=4, col=1)
# fig.add_hline(y=-80, row=4, col=1, line_dash="dot", line_color="red")
# fig.add_hline(y=-20, row=4, col=1, line_dash="dot", line_color="green")
# add_segmented_line(fig, plot_df, "acceleration_5_3_1", "acceleration_5_3_1", 5, "#2ca02c", width=2)
# add_segmented_line(fig, plot_df, "rsi_3", "RSI 3", 5, "#2ca02c", width=2)
# add_segmented_line(fig, plot_df, "vortex_plus_14", "Vortex 14 plus", 5, "#2ca02c", width=2)
# add_segmented_line(fig, plot_df, "vortex_minus_14", "Vortex 14 minus", 5, "#96280c", width=2)
add_segmented_line(fig, plot_df, "mean_vol_100", "Mean Vol 100", 2, "#96280c", width=2)


# Una marca de eje por inicio de cada día y ticker.
day_starts = (
    plot_df
    .group_by(GROUPS, maintain_order=True)
    .agg(pl.col("plot_x").min().alias("plot_x"))
    .sort("plot_x")
)

fig.update_xaxes(
    tickmode="array",
    tickvals=day_starts["plot_x"].to_list(),
    ticktext=[
        f"{row['ticker']}<br>{row['trading_day']}"
        for row in day_starts.to_dicts()
    ],
    row=5,
    col=1,
)

# Etiqueta centrada sobre cada tramo de ticker.
ticker_ranges = (
    plot_df
    .group_by("ticker", maintain_order=True)
    .agg(
        pl.col("plot_x").min().alias("start"),
        pl.col("plot_x").max().alias("end"),
    )
)

# for ticker_range in ticker_ranges.to_dicts():
#     fig.add_annotation(
#         x=(ticker_range["start"] + ticker_range["end"]) / 2,
#         y=1.03,
#         xref="x",
#         yref="paper",
#         text=f"<b>{ticker_range['ticker']}</b>",
#         showarrow=False,
#     )
hover_labels = {
    row["plot_x"]: (
        f"<b>{row['ticker']}</b><br>"
        f"{row['datetime'].strftime('%d/%m/%Y %H:%M:%S %Z')}"
    )
    for row in plot_df.select(
        "plot_x", "ticker", "datetime"
    ).iter_rows(named=True)
}

for trace in fig.data:
    if trace.type not in ("candlestick", "scatter", "bar"):
        continue

    labels = [hover_labels[x] for x in trace.x]

    if trace.type == "candlestick":
        trace.update(
            hovertext=[
                (
                    f"{label}<br>"
                    f"Apertura: {o:.4f}<br>"
                    f"Máximo: {h:.4f}<br>"
                    f"Mínimo: {l:.4f}<br>"
                    f"Cierre: {c:.4f}"
                )
                for label, o, h, l, c in zip(
                    labels,
                    trace.open,
                    trace.high,
                    trace.low,
                    trace.close,
                )
            ],
            hoverinfo="text",
        )
    else:
        trace.update(
            text=labels,
            hovertemplate=(
                "%{text}<br>"
                "Valor: %{y:,.4f}"
                "<extra>%{fullData.name}</extra>"
            ),
        )
fig.update_xaxes(
    showspikes=True,
    spikesnap="cursor",
    spikemode="across",
    spikecolor="#808080",
    spikethickness=1,
)

fig.update_layout(
    xaxis_rangeslider_visible=False,
    hovermode="x",
    # hoversubplots="axis",
    height=1_300,
    spikedistance=-1,
)

fig.show()

Conversion de data para backtesting

In [ ]:
df_to_plot

shape: (2_704, 22)
┌─────────────┬────────┬────────┬────────┬───┬───────────┬─────────────┬─────────────┬─────────────┐
│ datetime    ┆ ticker ┆ open   ┆ high   ┆ … ┆ roc_10    ┆ bb_middle_5 ┆ bb_upper_50 ┆ bb_lower_50 │
│ ---         ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---       ┆ 0           ┆ ---         ┆ ---         │
│ datetime[μs ┆ str    ┆ f64    ┆ f64    ┆   ┆ f64       ┆ ---         ┆ f64         ┆ f64         │
│ , America/N ┆        ┆        ┆        ┆   ┆           ┆ f64         ┆             ┆             │
│ ew_York]    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
╞═════════════╪════════╪════════╪════════╪═══╪═══════════╪═════════════╪═════════════╪═════════════╡
│ 2026-10-13  ┆ TCRT   ┆ 1.0    ┆ 1.01   ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:00:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-13  ┆ TCRT   ┆ 0.9905 ┆ 1.02   ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:03:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-13  ┆ TCRT   ┆ 0.9896 ┆ 1.0    ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:04:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-13  ┆ TCRT   ┆ 1.03   ┆ 1.05   ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:09:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-13  ┆ TCRT   ┆ 1.0499 ┆ 1.0499 ┆ … ┆ null      ┆ null        ┆ null        ┆ null        │
│ 04:14:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ …           ┆ …      ┆ …      ┆ …      ┆ … ┆ …         ┆ …           ┆ …           ┆ …           │
│ 2026-10-09  ┆ VEEA   ┆ 5.04   ┆ 5.05   ┆ … ┆ 0.714488  ┆ 4.914584    ┆ 5.080254    ┆ 4.748915    │
│ 19:55:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-09  ┆ VEEA   ┆ 4.98   ┆ 4.98   ┆ … ┆ -1.0      ┆ 4.915973    ┆ 5.08031     ┆ 4.751636    │
│ 19:56:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-09  ┆ VEEA   ┆ 4.98   ┆ 4.98   ┆ … ┆ 0.201207  ┆ 4.918484    ┆ 5.08357     ┆ 4.753398    │
│ 19:57:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-09  ┆ VEEA   ┆ 5.0    ┆ 5.01   ┆ … ┆ -0.795229 ┆ 4.921288    ┆ 5.086917    ┆ 4.75566     │
│ 19:58:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ 2026-10-09  ┆ VEEA   ┆ 4.9901 ┆ 5.01   ┆ … ┆ 1.829268  ┆ 4.924767    ┆ 5.093134    ┆ 4.756401    │
│ 19:59:00    ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
│ EDT         ┆        ┆        ┆        ┆   ┆           ┆             ┆             ┆             │
└─────────────┴────────┴────────┴────────┴───┴───────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
# [c[0].upper()+c[1:].lower() for c in df_to_plot.columns]

In [ ]:
data = df_to_plot.filter(pl.col('ticker')=="VEEA")
# .filter(pl.col('datetime').dt.date()>=date.fromisoformat('2026-10-04'))
data.columns = [c[0].upper()+c[1:].lower() for c in df_to_plot.columns]
data = data.to_pandas().set_index('Datetime')
data

,Ticker,Open,High,Low,Close,Volume,Trading_day,Price,Vwap_daily,Atr_14,...,Donchian_upper_50,Donchian_lower_50,Donchian_middle_50,Momentum_10,Mean_vol_100,Ema_50,Roc_10,Bb_middle_50,Bb_upper_50,Bb_lower_50
Datetime,,,,,,,,,,,,,,,,,,,,,
2026-10-05 04:00:00-04:00,VEEA,4.3100,4.7406,4.1500,4.1500,78893,2026-10-05,4.346867,4.346867,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-10-05 04:01:00-04:00,VEEA,4.1500,4.5800,4.1500,4.1506,35747,2026-10-05,4.293533,4.330236,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-10-05 04:02:00-04:00,VEEA,4.1593,4.7600,4.1304,4.3900,381615,2026-10-05,4.426800,4.404493,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-10-05 04:03:00-04:00,VEEA,4.3900,4.4900,4.1000,4.1004,63551,2026-10-05,4.230133,4.384699,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-10-05 04:04:00-04:00,VEEA,4.1005,4.1100,4.0910,4.0910,13072,2026-10-05,4.097333,4.378142,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-10-09 19:55:00-04:00,VEEA,5.0400,5.0500,4.9900,4.9900,5726,2026-10-09,5.010000,5.931664,0.062907,...,5.09,4.7762,4.9331,0.0354,2312.00,4.914584,0.714488,4.914584,5.080254,4.748915
2026-10-09 19:56:00-04:00,VEEA,4.9800,4.9800,4.9500,4.9500,4462,2026-10-09,4.960000,5.931612,0.060050,...,5.09,4.7762,4.9331,-0.0500,2346.11,4.915973,-1.000000,4.915973,5.080310,4.751636
2026-10-09 19:57:00-04:00,VEEA,4.9800,4.9800,4.9715,4.9800,1456,2026-10-09,4.977167,5.931596,0.058764,...,5.09,4.7762,4.9331,0.0100,2356.40,4.918484,0.201207,4.918484,5.083570,4.753398
2026-10-09 19:58:00-04:00,VEEA,5.0000,5.0100,4.9900,4.9900,5081,2026-10-09,4.996667,5.931539,0.057336,...,5.09,4.7762,4.9331,-0.0400,2358.28,4.921288,-0.795229,4.921288,5.086917,4.755660
2026-10-09 19:59:00-04:00,VEEA,4.9901,5.0100,4.9800,5.0100,5599,2026-10-09,5.000000,5.931476,0.053886,...,5.09,4.7762,4.9331,0.0900,2369.96,4.924767,1.829268,4.924767,5.093134,4.756401

In [ ]:
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
import numpy as np
from backtesting.test import SMA, GOOG


class VwapCross(Strategy):


    max_bars = 5
    valor_R=2
    # def bollinger_bands_indicator(self):
    #     return np.vstack(
    #         (
    #             self.data.Bb_upper_20,
    #             self.data.Bb_middle_20,
    #             self.data.Bb_lower_20,
    #         )
    #     )
    # def donchian_channels_indicator(self):
    #         return np.vstack(
    #             (
    #                 self.data.Donchian_upper_20	,
    #                 self.data.Donchian_lower_20,
    #                 self.data.Donchian_middle_20,
    #             )
    #         )
    
    def vwap_indicator(self):
        return self.data.Vwap_daily
    def atr_indicator(self):
            return self.data.Atr_14
    # def momentum_indicator(self):
    #         return self.data.Momentum_10
    def rsi_indicator(self):
         return self.data.Rsi_14
    def init(self):
        price = self.data.Close
        self.vwap = self.I(self.vwap_indicator)
        # self.atr = self.I(self.atr_indicator)
        # self.momentum= self.I(self.momentum_indicator)
        self.rsi = self.I(self.rsi_indicator)
        self.ema50 = self.I( 
            np.asarray,
            self.data.Ema_50,
            name="EMA 50",
            overlay=True,)
        self.roc10 = self.I( 
                    np.asarray,
                    self.data.Roc_10,
                    name="ROC 10",
                    overlay=False,)


        # self.bb_upper, self.bb_middle, self.bb_lower = self.I(
        #     self.bollinger_bands_indicator,
        #     name=("BB superior", "BB media", "BB inferior"),
        #     overlay=True,
        # )
        # self.donchian_upper, self.donchian_middle, self.donchian_lower = self.I(
        #     self.donchian_channels_indicator,
        #     name=("donchian superior", "donchian media", "donchian inferior"),
        #     overlay=True,
        # )
        self.nbars=0
        # self.ma2 = self.I(SMA, price, 20)
        self.data_ant=None

    def next(self):
        # if crossover(self.data.Close, self.data.Vwap_daily) and not self.position.is_long:
        if self.data.Close[-1]> self.data.Vwap_daily[-1] and self.data.Close[-2]< self.data.Vwap_daily[-2] and not self.trades and not self.orders:
            recent_volumes = self.data.Volume[-4:-1]
            if len(recent_volumes) == 3 and (
                self.data.Volume[-1] * 30 >= sum(recent_volumes) * 11
            ):
                # sl= self.data.Low[-3:].min()
                # tp =self.data.Close+ (self.data.Close-sl)*2
                sl= self.data.Close[-1]-self.data.Atr_14[-1]*2
                sl2= self.data.Close[-1]-self.data.Atr_14[-1]*2
                sl3= self.data.Close[-1]-self.data.Atr_14[-1]*2
                tp =self.data.Close[-1]+self.data.Atr_14[-1]*2
                tp2 =self.data.Close[-1]+self.data.Atr_14[-1]*3
                tp3 =self.data.Close[-1]+self.data.Atr_14[-1]*6
                self.nbars=0
                if sl>0 and tp>0:
                    # print(self.data.Close[-1],sl,tp)

                    size = int(self.valor_R/(self.data.Close[-1]-sl))
                    size2=int (size/4)
                    size3=int (size/4)
                    size1 = size-size2-size3
                    # print(size)
                    # print(self.data.Close[-1],sl,tp,size,size1,size2,size3)
                    # self.buy(sl=sl,tp=tp,size=size1)
                    # self.buy(sl=sl2,tp=tp2,size=size2)
                    # self.buy(sl=sl3,tp=tp3,size=size3)
                    if size1>0 and size2>0 and size3>0: 
                        self.buy(sl=sl, tp=tp, size=size1, tag="salida 1")
                        self.buy(sl=sl2, size=size2, tag="salida 2")
                        self.buy(sl=sl3, size=size3, tag="salida 3")

        open_price = self.data.Open[-1]
        high_price = self.data.High[-1]
        low_price = self.data.Low[-1]
        close_price = self.data.Close[-1]
        previous_open = self.data.Open[-2]
        previous_close = self.data.Close[-2]
        
        body = abs(close_price - open_price)
        upper_wick = high_price - max(open_price, close_price)
        lower_wick = min(open_price, close_price) - low_price
        upper_wick_signal = (
            body > 0
            and upper_wick > body * 3
            and lower_wick < upper_wick*1.5
        )

        bearish_engulfing_signal = (
            previous_close > previous_open      # vela anterior alcista
            and close_price < open_price        # vela actual bajista
            and open_price >= previous_close    # abre por encima del cierre previo
            and close_price <= previous_open    # cierra por debajo de la apertura previa
            and body > abs(previous_close - previous_open)
        )

        salida_1_abierta = any(
            trade.tag == "salida 1" for trade in self.trades
        )

        if not salida_1_abierta:
            for trade in self.trades:
                if trade.tag == "salida 2" and upper_wick_signal:
                    trade.close()

                if trade.tag == "salida 3" and bearish_engulfing_signal:
                    trade.close()
                # elif crossover(self.data.Close, self.data.vwap_daily):
                    # self.sell()
                # if self.position.is_long:
                #     self.nbars+=1
                #     if self.nbars>=self.max_bars:
                        
                #         self.position.close()
                self.data_ant = self.data

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\backtesting\_plotting.py:55: UserWarning:

Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support, such as old IDEs. Reset with `backtesting.set_bokeh_output(notebook=False)`.

In [ ]:
bt = Backtest(data, VwapCross, 
              commission=(0.001, 0),
            #   commission=(.001,0) 
              cash=500,
              exclusive_orders=False)
stats = bt.run(valor_R = 2)
stats
bt.plot()

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

GridPlot(id='p1413', ...)

In [ ]:
import numpy as np
from backtesting import Backtest, Strategy


class VWAPCROSS_ROC_OUTPUT(Strategy):
    valor_R = 2.0
    comision_fija = 0.001
    debug = True

    def init(self):
        self.vwap = self.I(
            np.asarray, self.data.Vwap_daily,
            name="VWAP", overlay=True,
        )
        self.ema50 = self.I(
            np.asarray, self.data.Ema_50,
            name="EMA 50", overlay=True,
        )
        self.roc10 = self.I(
            np.asarray, self.data.Roc_10,
            name="ROC 10", overlay=False,
        )

        self._closed_at_entry = 0
        self._reported_closed = 0
        self._roc_exits = {}
        self.logs = []

        if not np.isfinite(self.valor_R) or self.valor_R <= 0:
            raise ValueError("valor_R debe ser positivo")

    def _log(self, event, message, timestamp=None):
        if timestamp is None:
            timestamp = self.data.index[-1]

        text = f"{timestamp} | {event} | {message}"
        self.logs.append(text)

        if self.debug:
            print(text)

    def report_closed_trades(self):
        for trade in self.closed_trades[self._reported_closed:]:
            reason = self._roc_exits.pop(id(trade), None)

            if reason is None:
                if trade.sl is not None and trade.exit_price <= trade.sl:
                    if np.isclose(
                        trade.sl, trade.entry_price, rtol=0, atol=1e-10
                    ):
                        reason = "Stop en breakeven (inferido)"
                    else:
                        reason = "Stop loss (inferido)"
                elif trade.tp is not None and trade.exit_price >= trade.tp:
                    reason = "Take profit (inferido)"
                else:
                    reason = "Motivo automático no determinado"

            self._log(
                "CIERRE EJECUTADO",
                f"{trade.tag} | {reason} | "
                f"entrada={trade.entry_price:.4f} | "
                f"salida={trade.exit_price:.4f} | "
                f"acciones={trade.size} | P/L={trade.pl:.4f}",
                timestamp=trade.exit_time,
            )

        self._reported_closed = len(self.closed_trades)

    def next(self):
        self.report_closed_trades()

        if self.trades:
            roc = self.roc10[-4:]
            roc_description = "ROC insuficiente o no válido"

            if len(roc) == 4 and np.isfinite(roc).all():
                roc_mean = float(np.mean(roc[:-1]))
                roc_description = (
                    f"ROC actual={roc[-1]:.4f}, "
                    f"media de los 3 anteriores={roc_mean:.4f}"
                )

                if roc[-1] < roc_mean:
                    for trade in self.trades:
                        reason = f"Salida por ROC: {roc_description}"
                        self._roc_exits[id(trade)] = reason
                        self._log(
                            "SOLICITUD DE CIERRE",
                            f"{trade.tag} | {reason}",
                        )
                        trade.close()
                    return

            first_closed = any(
                trade.tag == "salida 1"
                for trade in self.closed_trades[self._closed_at_entry:]
            )

            if first_closed:
                for trade in self.trades:
                    if trade.tag in ("salida 2", "salida 3"):
                        new_sl = max(trade.sl or 0, trade.entry_price)

                        if trade.sl != new_sl:
                            previous_sl = trade.sl
                            trade.sl = new_sl
                            self._log(
                                "BREAKEVEN",
                                f"{trade.tag} | cerró salida 1 | "
                                f"SL anterior={previous_sl} | "
                                f"nuevo SL={new_sl:.4f}",
                            )

            self._log(
                "SIN NUEVA ENTRADA",
                f"Hay {len(self.trades)} posiciones abiertas | "
                f"{roc_description}",
            )
            return

        if self.orders:
            self._log(
                "SIN ENTRADA",
                f"Hay {len(self.orders)} órdenes pendientes",
            )
            return

        if len(self.data) < 2:
            self._log("SIN ENTRADA", "Falta una vela anterior")
            return

        close = float(self.data.Close[-1])
        open_ = float(self.data.Open[-1])
        vwap = float(self.vwap[-1])
        ema = float(self.ema50[-1])
        atr = float(self.data.Atr_14[-1])
        volume = float(self.data.Volume[-1])
        volume_mean = float(self.data.Mean_vol_100[-1])
        previous_close = float(self.data.Close[-2])
        previous_vwap = float(self.vwap[-2])
        previous_ema = float(self.ema50[-2])

        values = {
            "close": close,
            "open": open_,
            "VWAP": vwap,
            "EMA50": ema,
            "ATR": atr,
            "volumen": volume,
            "media_volumen": volume_mean,
            "cierre_anterior": previous_close,
            "VWAP_anterior": previous_vwap,
        }

        invalid = [
            name for name, value in values.items()
            if not np.isfinite(value)
        ]

        if invalid:
            self._log(
                "SIN ENTRADA",
                "Datos no válidos o sin calentamiento: " + ", ".join(invalid),
            )
            return

        if atr <= 0 or close <= 0:
            self._log(
                "SIN ENTRADA",
                f"ATR o precio no positivo: ATR={atr}, close={close}",
            )
            return

        vwap_cross_up = (
            previous_close <= previous_vwap 
            and close > vwap
            
        )
        ema_cross_up = (
                    previous_close <= previous_ema
                    and close > ema
                    
                )

        checks = [
            (
                close > previous_close,
                f"El cierre no supera al anterior "
                f"({close:.4f} <= {previous_close:.4f})",
            ),
            (
                vwap_cross_up,
                f"No hay cruce alcista de VWAP "
                f"(cierre anterior={previous_close:.4f}, "
                f"VWAP anterior={previous_vwap:.4f}, "
                f"cierre={close:.4f}, VWAP={vwap:.4f})",
            ),
            (
                close > ema,
                f"El cierre no supera EMA50 "
                f"({close:.4f} <= {ema:.4f})",
            ),
            (
                volume > volume_mean,
                f"El volumen no supera su media "
                f"({volume:.0f} <= {volume_mean:.2f})",
            ),
            (
                vwap > ema,
                f"VWAP no supera EMA50 ({vwap:.4f} <= {ema:.4f})",
            ),
        ]

        # checks = [
        #     (
        #         close > previous_close,
        #         f"El cierre no supera al anterior "
        #         f"({close:.4f} <= {previous_close:.4f})",
        #     ),
        #     (
        #         ema_cross_up,
        #         f"No hay cruce alcista de Ema "
        #         f"(cierre anterior={previous_close:.4f}, "
        #         f"Ema anterior={previous_ema:.4f}, "
        #         f"cierre={close:.4f}, VWAP={ema:.4f})",
        #     ),
        #     (
        #         close > vwap,
        #         f"El cierre no supera VWAP "
        #         f"({close:.4f} <= {ema:.4f})",
        #     ),
        #     (
        #         volume > volume_mean,
        #         f"El volumen no supera su media "
        #         f"({volume:.0f} <= {volume_mean:.2f})",
        #     ),
        #     (
        #         vwap < ema,
        #         f"VWAP no supera EMA50 ({vwap:.4f} <= {ema:.4f})",
        #     ),
        #     (
        #         vwap < ema,
        #         f"VWAP no supera EMA50 ({vwap:.4f} <= {ema:.4f})",
        #     ),
        # ]
        
        failed = [reason for passed, reason in checks if not passed]

        if failed:
            self._log("SIN ENTRADA", " | ".join(failed))
            return

        sl = close - 2 * atr

        if sl <= 0:
            self._log(
                "SIN ENTRADA",
                f"El stop calculado no es positivo: SL={sl:.4f}",
            )
            return

        max_risk_size = int(self.valor_R / (2 * atr))
        max_cash_size = max(
            0,
            int((self.equity - 6 * self.comision_fija) / close),
        )
        quarter = min(max_risk_size, max_cash_size) // 4

        if quarter < 1:
            self._log(
                "SIN ENTRADA",
                f"No alcanza para repartir 4 acciones | "
                f"máximo por riesgo={max_risk_size} | "
                f"máximo por capital={max_cash_size} | ATR={atr:.4f}",
            )
            return

        self._closed_at_entry = len(self.closed_trades)
        # self._log('****ENTRADA ',
        #          f"Vwap previa: {previous_vwap}| Vwap {vwap} |",
        #          f"close previo: {previous_close}| Close {close} | {self.data.Close[-1]}")
        self.buy(
            size=2 * quarter,
            sl=sl,
            tp=close + 4 * atr,
            tag="salida 1",
        )
        self.buy(
            size=quarter,
            sl=sl,
            tp=close + 6 * atr,
            tag="salida 2",
        )
        self.buy(
            size=quarter,
            sl=sl,
            tag="salida 3",
        )

        self._log(
            "ENTRADA SOLICITADA",
            f"Todos los filtros cumplidos: cierre creciente, cruce VWAP, "
            f"cierre sobre EMA50, volumen superior a su media y VWAP sobre EMA50 | "
            f"precio de referencia={close:.4f} | "
            f"acciones={2 * quarter}/{quarter}/{quarter} | "
            f"SL={sl:.4f} | TP1={close + 4 * atr:.4f} | "
            f"TP2={close + 6 * atr:.4f}",
        )

In [ ]:
bt = Backtest(data, VWAPCROSS_ROC_OUTPUT, 
              commission=(0.001, 0),
            #   commission=(.001,0) 
              cash=500,
              exclusive_orders=False)
stats = bt.run(
    valor_R=10,
    comision_fija=0.001,
    debug=True,
)

stats["_strategy"].report_closed_trades()
# stats = bt.run(valor_R = 10)

bt.plot()

2026-10-05 04:50:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:51:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:52:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:53:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:54:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:55:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:56:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:57:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:58:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:59:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:00:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:01:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:02:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:03:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:04:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:05:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:06:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:07:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:08:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:09:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:10:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:11:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:12:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:13:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:14:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:15:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:16:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:17:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:18:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:19:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:20:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:21:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:22:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:23:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:24:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:25:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:26:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:27:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:28:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:29:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:30:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:31:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:32:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:33:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:34:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:35:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:36:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:37:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:38:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:39:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5900 <= 4.6400) | No hay cruce alcista de VWAP (cierre anterior=4.6400, VWAP anterior=4.7534, cierre=4.5900, VWAP=4.7527) | El cierre no supera EMA50 (4.5900 <= 4.6870) | El volumen no supera su media (35482 <= 67608.29)
2026-10-05 05:40:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5900, VWAP anterior=4.7527, cierre=4.6100, VWAP=4.7523) | El cierre no supera EMA50 (4.6100 <= 4.6840) | El volumen no supera su media (17226 <= 66991.62)
2026-10-05 05:41:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6100, VWAP anterior=4.7523, cierre=4.7051, VWAP=4.7521) | El volumen no supera su media (18170 <= 66815.85)
2026-10-05 05:42:00-04:00 | ENTRADA SOLICITADA | Todos los filtros cumplidos: cierre creciente, cruce VWAP, cierre sobre EMA50, volumen superior a su media y VWAP sobre EMA50 | precio de referencia=4.7779 | acciones=22/11/11 | SL=4.5686 | TP1=5.1965 | TP2=5.4058
2026-10-05 05:43:00-04:00 | SIN NUEVA ENTRADA | Hay 3 posiciones abiertas | ROC actual=4.8694, media de los 3 anteriores=0.6607
2026-10-05 05:44:00-04:00 | SOLICITUD DE CIERRE | salida 1 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032
2026-10-05 05:44:00-04:00 | SOLICITUD DE CIERRE | salida 2 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032
2026-10-05 05:44:00-04:00 | SOLICITUD DE CIERRE | salida 3 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032
2026-10-05 05:45:00-04:00 | CIERRE EJECUTADO | salida 3 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032 | entrada=4.7602 | salida=4.6903 | acciones=11 | P/L=-0.7709
2026-10-05 05:45:00-04:00 | CIERRE EJECUTADO | salida 2 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032 | entrada=4.7602 | salida=4.6903 | acciones=11 | P/L=-0.7709
2026-10-05 05:45:00-04:00 | CIERRE EJECUTADO | salida 1 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032 | entrada=4.7602 | salida=4.6903 | acciones=22 | P/L=-1.5398
2026-10-05 05:45:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6906, VWAP anterior=4.7519, cierre=4.7204, VWAP=4.7518) | El volumen no supera su media (13968 <= 63860.75)
2026-10-05 05:46:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7200 <= 4.7204) | No hay cruce alcista de VWAP (cierre anterior=4.7204, VWAP anterior=4.7518, cierre=4.7200, VWAP=4.7517) | El volumen no supera su media (11876 <= 63872.10)
2026-10-05 05:47:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7113 <= 4.7200) | No hay cruce alcista de VWAP (cierre anterior=4.7200, VWAP anterior=4.7517, cierre=4.7113, VWAP=4.7517) | El volumen no supera su media (22400 <= 64063.48)
2026-10-05 05:48:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7000 <= 4.7113) | No hay cruce alcista de VWAP (cierre anterior=4.7113, VWAP anterior=4.7517, cierre=4.7000, VWAP=4.7515) | El volumen no supera su media (28170 <= 64113.64)
2026-10-05 05:49:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7000 <= 4.7000) | No hay cruce alcista de VWAP (cierre anterior=4.7000, VWAP anterior=4.7515, cierre=4.7000, VWAP=4.7513) | El volumen no supera su media (18301 <= 64081.06)
2026-10-05 05:50:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6700 <= 4.7000) | No hay cruce alcista de VWAP (cierre anterior=4.7000, VWAP anterior=4.7513, cierre=4.6700, VWAP=4.7511) | El cierre no supera EMA50 (4.6700 <= 4.6930) | El volumen no supera su media (24085 <= 64180.19)
2026-10-05 05:51:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5894 <= 4.6700) | No hay cruce alcista de VWAP (cierre anterior=4.6700, VWAP anterior=4.7511, cierre=4.5894, VWAP=4.7504) | El cierre no supera EMA50 (4.5894 <= 4.6890) | El volumen no supera su media (38554 <= 64348.55)
2026-10-05 05:52:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5894, VWAP anterior=4.7504, cierre=4.6488, VWAP=4.7501) | El cierre no supera EMA50 (4.6488 <= 4.6874) | El volumen no supera su media (14029 <= 64329.92)
2026-10-05 05:53:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6488, VWAP anterior=4.7501, cierre=4.6600, VWAP=4.7499) | El cierre no supera EMA50 (4.6600 <= 4.6863) | El volumen no supera su media (13852 <= 64394.27)
2026-10-05 05:54:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6600, VWAP anterior=4.7499, cierre=4.6999, VWAP=4.7498) | El volumen no supera su media (9333 <= 64395.54)
2026-10-05 05:55:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6999, VWAP anterior=4.7498, cierre=4.7400, VWAP=4.7498) | El volumen no supera su media (22077 <= 64584.64)
2026-10-05 05:56:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7300 <= 4.7400) | No hay cruce alcista de VWAP (cierre anterior=4.7400, VWAP anterior=4.7498, cierre=4.7300, VWAP=4.7497) | El volumen no supera su media (18696 <= 64429.36)
2026-10-05 05:57:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6883 <= 4.7300) | No hay cruce alcista de VWAP (cierre anterior=4.7300, VWAP anterior=4.7497, cierre=4.6883, VWAP=4.7496) | El cierre no supera EMA50 (4.6883 <= 4.6905) | El volumen no supera su media (34763 <= 64677.73)
2026-10-05 05:58:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6883, VWAP anterior=4.7496, cierre=4.7200, VWAP=4.7495) | El volumen no supera su media (8283 <= 64674.23)
2026-10-05 05:59:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7100 <= 4.7200) | No hay cruce alcista de VWAP (cierre anterior=4.7200, VWAP anterior=4.7495, cierre=4.7100, VWAP=4.7495) | El volumen no supera su media (8126 <= 64589.67)
2026-10-05 06:00:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.7100, VWAP anterior=4.7495, cierre=4.7101, VWAP=4.7494) | El volumen no supera su media (7517 <= 64390.02)
2026-10-05 06:01:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6900 <= 4.7101) | No hay cruce alcista de VWAP (cierre anterior=4.7101, VWAP anterior=4.7494, cierre=4.6900, VWAP=4.7493) | El cierre no supera EMA50 (4.6900 <= 4.6929) | El volumen no supera su media (15247 <= 64377.51)
2026-10-05 06:02:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6900, VWAP anterior=4.7493, cierre=4.7000, VWAP=4.7493) | El volumen no supera su media (8981 <= 64362.95)
2026-10-05 06:03:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6600 <= 4.7000) | No hay cruce alcista de VWAP (cierre anterior=4.7000, VWAP anterior=4.7493, cierre=4.6600, VWAP=4.7491) | El cierre no supera EMA50 (4.6600 <= 4.6919) | El volumen no supera su media (15738 <= 64384.25)
2026-10-05 06:04:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6200 <= 4.6600) | No hay cruce alcista de VWAP (cierre anterior=4.6600, VWAP anterior=4.7491, cierre=4.6200, VWAP=4.7488) | El cierre no supera EMA50 (4.6200 <= 4.6891) | El volumen no supera su media (15060 <= 64326.03)
2026-10-05 06:05:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6200, VWAP anterior=4.7488, cierre=4.6400, VWAP=4.7487) | El cierre no supera EMA50 (4.6400 <= 4.6872) | El volumen no supera su media (9378 <= 64360.08)
2026-10-05 06:06:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5900 <= 4.6400) | No hay cruce alcista de VWAP (cierre anterior=4.6400, VWAP anterior=4.7487, cierre=4.5900, VWAP=4.7483) | El cierre no supera EMA50 (4.5900 <= 4.6833) | El volumen no supera su media (22168 <= 64465.85)
2026-10-05 06:07:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5900, VWAP anterior=4.7483, cierre=4.6000, VWAP=4.7481) | El cierre no supera EMA50 (4.6000 <= 4.6801) | El volumen no supera su media (9724 <= 64435.38)
2026-10-05 06:08:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5900 <= 4.6000) | No hay cruce alcista de VWAP (cierre anterior=4.6000, VWAP anterior=4.7481, cierre=4.5900, VWAP=4.7479) | El cierre no supera EMA50 (4.5900 <= 4.6765) | El volumen no supera su media (9006 <= 64389.63)
2026-10-05 06:09:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5900, VWAP anterior=4.7479, cierre=4.6382, VWAP=4.7477) | El cierre no supera EMA50 (4.6382 <= 4.6750) | El volumen no supera su media (8668 <= 64417.86)
2026-10-05 06:10:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6000 <= 4.6382) | No hay cruce alcista de VWAP (cierre anterior=4.6382, VWAP anterior=4.7477, cierre=4.6000, VWAP=4.7476) | El cierre no supera EMA50 (4.6000 <= 4.6721) | El volumen no supera su media (7320 <= 64381.55)
2026-10-05 06:11:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5803 <= 4.6000) | No hay cruce alcista de VWAP (cierre anterior=4.6000, VWAP anterior=4.7476, cierre=4.5803, VWAP=4.7475) | El cierre no supera EMA50 (4.5803 <= 4.6685) | El volumen no supera su media (5655 <= 64192.09)
2026-10-05 06:12:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5300 <= 4.5803) | No hay cruce alcista de VWAP (cierre anterior=4.5803, VWAP anterior=4.7475, cierre=4.5300, VWAP=4.7471) | El cierre no supera EMA50 (4.5300 <= 4.6631) | El volumen no supera su media (12264 <= 63954.05)
2026-10-05 06:13:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5300, VWAP anterior=4.7471, cierre=4.5543, VWAP=4.7466) | El cierre no supera EMA50 (4.5543 <= 4.6588) | El volumen no supera su media (19576 <= 63813.44)
2026-10-05 06:14:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5005 <= 4.5543) | No hay cruce alcista de VWAP (cierre anterior=4.5543, VWAP anterior=4.7466, cierre=4.5005, VWAP=4.7461) | El cierre no supera EMA50 (4.5005 <= 4.6526) | El volumen no supera su media (18122 <= 63813.93)
2026-10-05 06:15:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5005, VWAP anterior=4.7461, cierre=4.5400, VWAP=4.7454) | El cierre no supera EMA50 (4.5400 <= 4.6482) | El volumen no supera su media (23111 <= 63808.03)
2026-10-05 06:16:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5400, VWAP anterior=4.7454, cierre=4.5725, VWAP=4.7452) | El cierre no supera EMA50 (4.5725 <= 4.6452) | El volumen no supera su media (9511 <= 63721.68)
2026-10-05 06:17:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5604 <= 4.5725) | No hay cruce alcista de VWAP (cierre anterior=4.5725, VWAP anterior=4.7452, cierre=4.5604, VWAP=4.7448) | El cierre no supera EMA50 (4.5604 <= 4.6419) | El volumen no supera su media (13132 <= 63774.98)
2026-10-05 06:18:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5506 <= 4.5604) | No hay cruce alcista de VWAP (cierre anterior=4.5604, VWAP anterior=4.7448, cierre=4.5506, VWAP=4.7446) | El cierre no supera EMA50 (4.5506 <= 4.6383) | El volumen no supera su media (9977 <= 63799.13)
2026-10-05 06:19:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5300 <= 4.5506) | No hay cruce alcista de VWAP (cierre anterior=4.5506, VWAP anterior=4.7446, cierre=4.5300, VWAP=4.7442) | El cierre no supera EMA50 (4.5300 <= 4.6341) | El volumen no supera su media (14915 <= 63912.56)
2026-10-05 06:20:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.4499 <= 4.5300) | No hay cruce alcista de VWAP (cierre anterior=4.5300, VWAP anterior=4.7442, cierre=4.4499, VWAP=4.7434) | El cierre no supera EMA50 (4.4499 <= 4.6268) | El volumen no supera su media (20882 <= 64067.82)
2026-10-05 06:21:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.4499, VWAP anterior=4.7434, cierre=4.4700, VWAP=4.7429) | El cierre no supera EMA50 (4.4700 <= 4.6207) | El volumen no supera su media (13746 <= 64185.76)
2026-10-05 06:22:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.4700, VWAP anterior=4.7429, cierre=4.4900, VWAP=4.7426) | El cierre no supera EMA50 (4.4900 <= 4.6156) | El volumen no supera su media (9716 <= 64247.00)
2026-10-05 06:23:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.4900 <= 4.4900) | No hay cruce alcista de VWAP (cierre anterior=4.4900, VWAP anterior=4.7426, cierre=4.4900, VWAP=4.7422) | El cierre no supera EMA50 (4.4900 <= 4.6106) | El volumen no supera su media (12451 <= 64273.67)
2026-10-05 06:24:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.4899 <= 4.4900) | No hay cruce alcista de VWAP (cierre anterior=4.4900, VWAP anterior=4.7422, cierre=4.4899, VWAP=4.7418) | El cierre no supera EMA50 (4.4899 <= 4.6059) | El volumen no supera su media (12205 <= 64346.84)
2026-10-05 06:25:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.4800 <= 4.4899) | No hay cruce alcista de VWAP (cierre anterior=4.4899, VWAP anterior=4.7418, cierre=4.4800, VWAP=4.7415) | El cierre no supera EMA50 (4.4800 <= 4.6010) | El volumen no supera su media (6341 <= 64321.45)
2026-10-05 06:26:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.4800, VWAP anterior=4.7415, cierre=4.5200, VWAP=4.7409) | El cierre no supera EMA50 (4.5200 <= 4.5978) | El volumen no supera su media (19173 <= 64212.72)
2026-10-05 06:27:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5200, VWAP anterior=4.7409, cierre=4.5897, VWAP=4.7403) | El cierre no supera EMA50 (4.5897 <= 4.5975) | El volumen no supera su media (28232 <= 64138.79)
2026-10-05 06:28:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5897, VWAP anterior=4.7403, cierre=4.6300, VWAP=4.7397) | El volumen no supera su media (36220 <= 63907.69)
2026-10-05 06:29:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6000 <= 4.6300) | No hay cruce alcista de VWAP (cierre anterior=4.6300, VWAP anterior=4.7397, cierre=4.6000, VWAP=4.7395) | El volumen no supera su media (14707 <= 63136.60)
2026-10-05 06:30:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6000, VWAP anterior=4.7395, cierre=4.6019, VWAP=4.7391) | El volumen no supera su media (20188 <= 62781.35)
2026-10-05 06:31:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5897 <= 4.6019) | No hay cruce alcista de VWAP (cierre anterior=4.6019, VWAP anterior=4.7391, cierre=4.5897, VWAP=4.7389) | El cierre no supera EMA50 (4.5897 <= 4.5986) | El volumen no supera su media (12861 <= 62033.27)
2026-10-05 06:32:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5700 <= 4.5897) | No hay cruce alcista de VWAP (cierre anterior=4.5897, VWAP anterior=4.7389, cierre=4.5700, VWAP=4.7387) | El cierre no supera EMA50 (4.5700 <= 4.5974) | El volumen no supera su media (9513 <= 59955.05)
2026-10-05 06:33:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5586 <= 4.5700) | No hay cruce alcista de VWAP (cierre anterior=4.5700, VWAP anterior=4.7387, cierre=4.5586, VWAP=4.7385) | El cierre no supera EMA50 (4.5586 <= 4.5959) | El volumen no supera su media (8579 <= 57934.96)
2026-10-05 06:34:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5586, VWAP anterior=4.7385, cierre=4.5800, VWAP=4.7383) | El cierre no supera EMA50 (4.5800 <= 4.5953) | El volumen no supera su media (9451 <= 56637.31)
2026-10-05 06:35:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5800, VWAP anterior=4.7383, cierre=4.6600, VWAP=4.7377) | El volumen no supera su media (42032 <= 55983.80)

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

GridPlot(id='p1805', ...)

In [ ]:
stats

Start                     2026-10-05 04:00...
End                       2026-10-09 19:59...
Duration                      4 days 15:59:00
Exposure Time [%]                      2.0494
Equity Final [$]                    525.78143
Equity Peak [$]                     530.04243
Commissions [$]                          0.06
Return [%]                            5.15629
Buy & Hold Return [%]                15.16977
Return (Ann.) [%]                   -37.49818
Volatility (Ann.) [%]                      --
CAGR [%]                           5019.78379
Sharpe Ratio                               --
Sortino Ratio                       -12.67772
Calmar Ratio                        -20.25853
Alpha [%]                              5.0275
Beta                                  0.00849
Max. Drawdown [%]                    -1.85098
Avg. Drawdown [%]                    -1.20048
Max. Drawdown Duration        0 days 11:14:00
Avg. Drawdown Duration        0 days 04:22:00
# Trades                                   30
Win Rate [%]                             60.0
Best Trade [%]                        4.85249
Worst Trade [%]                      -1.87724
Avg. Trade [%]                        0.54049
Max. Trade Duration           0 days 00:06:00
Avg. Trade Duration           0 days 00:03:00
Profit Factor                         2.31435
Expectancy [%]                         0.5562
SQN                                   1.55878
Kelly Criterion                       0.37559
_strategy                 VWAPCROSS_ROC_OU...
_equity_curve                             ...
_trades                       Size  EntryB...
dtype: object

In [ ]:
stats._trades

,Size,EntryBar,ExitBar,EntryPrice,ExitPrice,SL,TP,PnL,Commission,ReturnPct,EntryTime,ExitTime,Duration,Tag,Entry_VWAP,Exit_VWAP,Entry_EMA 50,Exit_EMA 50,Entry_ROC 10,Exit_ROC 10
0,11,103,105,4.7602,4.690300,4.568600,NaN,-0.770900,0.002,-0.014722,2026-10-05 05:43:00-04:00,2026-10-05 05:45:00-04:00,0 days 00:02:00,salida 3,4.752022,4.751806,4.690472,4.691651,4.869361,2.840959
1,11,103,105,4.7602,4.690300,4.568600,5.405800,-0.770900,0.002,-0.014722,2026-10-05 05:43:00-04:00,2026-10-05 05:45:00-04:00,0 days 00:02:00,salida 2,4.752022,4.751806,4.690472,4.691651,4.869361,2.840959
2,22,103,105,4.7602,4.690300,4.568600,5.196500,-1.539800,0.002,-0.014703,2026-10-05 05:43:00-04:00,2026-10-05 05:45:00-04:00,0 days 00:02:00,salida 1,4.752022,4.751806,4.690472,4.691651,4.869361,2.840959
3,44,169,171,4.8204,5.043057,4.709371,5.043057,9.794914,0.002,0.046181,2026-10-05 06:49:00-04:00,2026-10-05 06:51:00-04:00,0 days 00:02:00,salida 1,4.737662,4.742581,4.620212,4.641053,7.236842,8.107221
4,22,169,175,4.8204,4.900400,4.820400,NaN,1.758000,0.002,0.016577,2026-10-05 06:49:00-04:00,2026-10-05 06:55:00-04:00,0 days 00:06:00,salida 3,4.737662,4.750827,4.620212,4.682174,7.236842,4.274298
5,22,169,175,4.8204,4.900400,4.820400,5.154286,1.758000,0.002,0.016577,2026-10-05 06:49:00-04:00,2026-10-05 06:55:00-04:00,0 days 00:06:00,salida 2,4.737662,4.750827,4.620212,4.682174,7.236842,4.274298
6,8,356,358,5.5600,5.580000,5.241529,NaN,0.158000,0.002,0.003552,2026-10-05 09:56:00-04:00,2026-10-05 09:58:00-04:00,0 days 00:02:00,salida 3,5.281313,5.291848,5.196907,5.229483,13.163819,9.176812
7,8,356,358,5.5600,5.580000,5.241529,6.475414,0.158000,0.002,0.003552,2026-10-05 09:56:00-04:00,2026-10-05 09:58:00-04:00,0 days 00:02:00,salida 2,5.281313,5.291848,5.196907,5.229483,13.163819,9.176812
8,16,356,358,5.5600,5.580000,5.241529,6.166943,0.318000,0.002,0.003575,2026-10-05 09:56:00-04:00,2026-10-05 09:58:00-04:00,0 days 00:02:00,salida 1,5.281313,5.291848,5.196907,5.229483,13.163819,9.176812
9,14,406,407,5.3300,5.310000,5.171486,NaN,-0.282000,0.002,-0.003779,2026-10-05 10:46:00-04:00,2026-10-05 10:47:00-04:00,0 days 00:01:00,salida 3,5.294108,5.294113,5.168360,5.174303,3.006790,3.299029
10,14,406,407,5.3300,5.310000,5.171486,5.839543,-0.282000,0.002,-0.003779,2026-10-05 10:46:00-04:00,2026-10-05 10:47:00-04:00,0 days 00:01:00,salida 2,5.294108,5.294113,5.168360,5.174303,3.006790,3.299029
11,28,406,407,5.3300,5.310000,5.171486,5.672529,-0.562000,0.002,-0.003766,2026-10-05 10:46:00-04:00,2026-10-05 10:47:00-04:00,0 days 00:01:00,salida 1,5.294108,5.294113,5.168360,5.174303,3.006790,3.299029
12,38,586,590,5.3199,5.578100,5.187500,5.578100,9.809600,0.002,0.048525,2026-10-05 13:46:00-04:00,2026-10-05 13:50:00-04:00,0 days 00:04:00,salida 1,5.269739,5.271604,5.065595,5.117665,5.030023,5.263158
13,19,586,591,5.3199,5.509900,5.187500,NaN,3.608000,0.002,0.035695,2026-10-05 13:46:00-04:00,2026-10-05 13:51:00-04:00,0 days 00:05:00,salida 3,5.269739,5.272191,5.065595,5.134032,5.030023,5.228137
14,19,586,591,5.3199,5.509900,5.187500,5.708300,3.608000,0.002,0.035695,2026-10-05 13:46:00-04:00,2026-10-05 13:51:00-04:00,0 days 00:05:00,salida 2,5.269739,5.272191,5.065595,5.134032,5.030023,5.228137
15,25,1086,1086,5.1950,5.097557,5.097557,NaN,-2.438071,0.002,-0.018772,2026-10-09 06:16:00-04:00,2026-10-09 06:16:00-04:00,0 days 00:00:00,salida 3,5.088508,5.088508,5.011504,5.011504,3.532258,3.532258
16,25,1086,1086,5.1950,5.097557,5.097557,5.467329,-2.438071,0.002,-0.018772,2026-10-09 06:16:00-04:00,2026-10-09 06:16:00-04:00,0 days 00:00:00,salida 2,5.088508,5.088508,5.011504,5.011504,3.532258,3.532258
17,50,1086,1086,5.1950,5.097557,5.097557,5.374886,-4.874143,0.002,-0.018765,2026-10-09 06:16:00-04:00,2026-10-09 06:16:00-04:00,0 days 00:00:00,salida 1,5.088508,5.088508,5.011504,5.011504,3.532258,3.532258
18,22,1232,1237,5.6204,5.700000,5.515214,NaN,1.749200,0.002,0.014147,2026-10-09 08:42:00-04:00,2026-10-09 08:47:00-04:00,0 days 00:05:00,salida 3,5.581696,5.586426,5.578099,5.602450,2.291633,2.900415
19,22,1232,1237,5.6204,5.700000,5.515214,5.934357,1.749200,0.002,0.014147,2026-10-09 08:42:00-04:00,2026-10-09 08:47:00-04:00,0 days 00:05:00,salida 2,5.581696,5.586426,5.578099,5.602450,2.291633,2.900415
20,44,1232,1237,5.6204,5.700000,5.515214,5.829571,3.500400,0.002,0.014155,2026-10-09 08:42:00-04:00,2026-10-09 08:47:00-04:00,0 days 00:05:00,salida 1,5.581696,5.586426,5.578099,5.602450,2.291633,2.900415
21,12,1613,1616,5.9600,5.930000,5.743771,NaN,-0.362000,0.002,-0.005062,2026-10-09 15:03:00-04:00,2026-10-09 15:06:00-04:00,0 days 00:03:00,salida 3,5.942167,5.942275,5.653496,5.692267,4.247788,7.042378
22,12,1613,1616,5.9600,5.930000,5.743771,6.548686,-0.362000,0.002,-0.005062,2026-10-09 15:03:00-04:00,2026-10-09 15:06:00-04:00,0 days 00:03:00,salida 2,5.942167,5.942275,5.653496,5.692267,4.247788,7.042378
23,24,1613,1616,5.9600,5.930000,5.743771,6.347457,-0.722000,0.002,-0.005048,2026-10-09 15:03:00-04:00,2026-10-09 15:06:00-04:00,0 days 00:03:00,salida 1,5.942167,5.942275,5.653496,5.692267,4.247788,7.042378
24,10,1617,1621,6.0650,6.138000,5.845486,NaN,0.728000,0.002,0.012003,2026-10-09 15:07:00-04:00,2026-10-09 15:11:00-04:00,0 days 00:04:00,salida 3,5.942633,5.943744,5.708649,5.766680,8.045977,8.893245
25,10,1617,1621,6.0650,6.138000,5.845486,6.783143,0.728000,0.002,0.012003,2026-10-09 15:07:00-04:00,2026-10-09 15:11:00-04:00,0 days 00:04:00,salida 2,5.942633,5.943744,5.708649,5.766680,8.045977,8.893245
26,20,1617,1621,6.0650,6.138000,5.845486,6.548729,1.458000,0.002,0.012020,2026-10-09 15:07:00-04:00,2026-10-09 15:11:00-04:00,0 days 00:04:00,salida 1,5.942633,5.943744,5.708649,5.766680,8.045977,8.893245
27,7,1624,1625,5.9690,5.980000,5.633429,NaN,0.075000,0.002,0.001795,2026-10-09 15:14:00-04:00,2026-10-09 15:15:00-04:00,0 days 00:01:00,salida 3,5.943879,5.943992,5.787351,5.796867,0.170717,1.686341
28,7,1624,1625,5.9690,5.980000,5.633429,6.939714,0.075000,0.002,0.001795,2026-10-09 15:14:00-04:00,2026-10-09 15:15:00-04:00,0 days 00:01:00,salida 2,5.943879,5.943992,5.787351,5.796867,0.170717,1.686341
29,14,1624,1625,5.9690,5.980000,5.633429,6.613143,0.152000,0.002,0.001819,2026-10-09 15:14:00-04:00,2026-10-09 15:15:00-04:00,0 days 00:01:00,salida 1,5.943879,5.943992,5.787351,5.796867,0.170717,1.686341

In [ ]:
for message in stats["_strategy"].logs:
    print(message)

2026-10-05 04:50:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:51:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:52:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:53:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:54:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:55:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:56:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:57:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:58:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 04:59:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:00:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:01:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:02:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:03:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:04:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:05:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:06:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:07:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:08:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:09:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:10:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:11:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:12:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:13:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:14:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:15:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:16:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:17:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:18:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:19:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:20:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:21:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:22:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:23:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:24:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:25:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:26:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:27:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:28:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:29:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:30:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:31:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:32:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:33:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:34:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:35:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:36:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:37:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:38:00-04:00 | SIN ENTRADA | Datos no válidos o sin calentamiento: media_volumen
2026-10-05 05:39:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5900 <= 4.6400) | No hay cruce alcista de VWAP (cierre anterior=4.6400, VWAP anterior=4.7534, cierre=4.5900, VWAP=4.7527) | El cierre no supera EMA50 (4.5900 <= 4.6870) | El volumen no supera su media (35482 <= 67608.29)
2026-10-05 05:40:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5900, VWAP anterior=4.7527, cierre=4.6100, VWAP=4.7523) | El cierre no supera EMA50 (4.6100 <= 4.6840) | El volumen no supera su media (17226 <= 66991.62)
2026-10-05 05:41:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6100, VWAP anterior=4.7523, cierre=4.7051, VWAP=4.7521) | El volumen no supera su media (18170 <= 66815.85)
2026-10-05 05:42:00-04:00 | ENTRADA SOLICITADA | Todos los filtros cumplidos: cierre creciente, cruce VWAP, cierre sobre EMA50, volumen superior a su media y VWAP sobre EMA50 | precio de referencia=4.7779 | acciones=22/11/11 | SL=4.5686 | TP1=5.1965 | TP2=5.4058
2026-10-05 05:43:00-04:00 | SIN NUEVA ENTRADA | Hay 3 posiciones abiertas | ROC actual=4.8694, media de los 3 anteriores=0.6607
2026-10-05 05:44:00-04:00 | SOLICITUD DE CIERRE | salida 1 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032
2026-10-05 05:44:00-04:00 | SOLICITUD DE CIERRE | salida 2 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032
2026-10-05 05:44:00-04:00 | SOLICITUD DE CIERRE | salida 3 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032
2026-10-05 05:45:00-04:00 | CIERRE EJECUTADO | salida 3 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032 | entrada=4.7602 | salida=4.6903 | acciones=11 | P/L=-0.7709
2026-10-05 05:45:00-04:00 | CIERRE EJECUTADO | salida 2 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032 | entrada=4.7602 | salida=4.6903 | acciones=11 | P/L=-0.7709
2026-10-05 05:45:00-04:00 | CIERRE EJECUTADO | salida 1 | Salida por ROC: ROC actual=1.4798, media de los 3 anteriores=3.6032 | entrada=4.7602 | salida=4.6903 | acciones=22 | P/L=-1.5398
2026-10-05 05:45:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6906, VWAP anterior=4.7519, cierre=4.7204, VWAP=4.7518) | El volumen no supera su media (13968 <= 63860.75)
2026-10-05 05:46:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7200 <= 4.7204) | No hay cruce alcista de VWAP (cierre anterior=4.7204, VWAP anterior=4.7518, cierre=4.7200, VWAP=4.7517) | El volumen no supera su media (11876 <= 63872.10)
2026-10-05 05:47:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7113 <= 4.7200) | No hay cruce alcista de VWAP (cierre anterior=4.7200, VWAP anterior=4.7517, cierre=4.7113, VWAP=4.7517) | El volumen no supera su media (22400 <= 64063.48)
2026-10-05 05:48:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7000 <= 4.7113) | No hay cruce alcista de VWAP (cierre anterior=4.7113, VWAP anterior=4.7517, cierre=4.7000, VWAP=4.7515) | El volumen no supera su media (28170 <= 64113.64)
2026-10-05 05:49:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7000 <= 4.7000) | No hay cruce alcista de VWAP (cierre anterior=4.7000, VWAP anterior=4.7515, cierre=4.7000, VWAP=4.7513) | El volumen no supera su media (18301 <= 64081.06)
2026-10-05 05:50:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6700 <= 4.7000) | No hay cruce alcista de VWAP (cierre anterior=4.7000, VWAP anterior=4.7513, cierre=4.6700, VWAP=4.7511) | El cierre no supera EMA50 (4.6700 <= 4.6930) | El volumen no supera su media (24085 <= 64180.19)
2026-10-05 05:51:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5894 <= 4.6700) | No hay cruce alcista de VWAP (cierre anterior=4.6700, VWAP anterior=4.7511, cierre=4.5894, VWAP=4.7504) | El cierre no supera EMA50 (4.5894 <= 4.6890) | El volumen no supera su media (38554 <= 64348.55)
2026-10-05 05:52:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5894, VWAP anterior=4.7504, cierre=4.6488, VWAP=4.7501) | El cierre no supera EMA50 (4.6488 <= 4.6874) | El volumen no supera su media (14029 <= 64329.92)
2026-10-05 05:53:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6488, VWAP anterior=4.7501, cierre=4.6600, VWAP=4.7499) | El cierre no supera EMA50 (4.6600 <= 4.6863) | El volumen no supera su media (13852 <= 64394.27)
2026-10-05 05:54:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6600, VWAP anterior=4.7499, cierre=4.6999, VWAP=4.7498) | El volumen no supera su media (9333 <= 64395.54)
2026-10-05 05:55:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6999, VWAP anterior=4.7498, cierre=4.7400, VWAP=4.7498) | El volumen no supera su media (22077 <= 64584.64)
2026-10-05 05:56:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7300 <= 4.7400) | No hay cruce alcista de VWAP (cierre anterior=4.7400, VWAP anterior=4.7498, cierre=4.7300, VWAP=4.7497) | El volumen no supera su media (18696 <= 64429.36)
2026-10-05 05:57:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6883 <= 4.7300) | No hay cruce alcista de VWAP (cierre anterior=4.7300, VWAP anterior=4.7497, cierre=4.6883, VWAP=4.7496) | El cierre no supera EMA50 (4.6883 <= 4.6905) | El volumen no supera su media (34763 <= 64677.73)
2026-10-05 05:58:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6883, VWAP anterior=4.7496, cierre=4.7200, VWAP=4.7495) | El volumen no supera su media (8283 <= 64674.23)
2026-10-05 05:59:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.7100 <= 4.7200) | No hay cruce alcista de VWAP (cierre anterior=4.7200, VWAP anterior=4.7495, cierre=4.7100, VWAP=4.7495) | El volumen no supera su media (8126 <= 64589.67)
2026-10-05 06:00:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.7100, VWAP anterior=4.7495, cierre=4.7101, VWAP=4.7494) | El volumen no supera su media (7517 <= 64390.02)
2026-10-05 06:01:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6900 <= 4.7101) | No hay cruce alcista de VWAP (cierre anterior=4.7101, VWAP anterior=4.7494, cierre=4.6900, VWAP=4.7493) | El cierre no supera EMA50 (4.6900 <= 4.6929) | El volumen no supera su media (15247 <= 64377.51)
2026-10-05 06:02:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6900, VWAP anterior=4.7493, cierre=4.7000, VWAP=4.7493) | El volumen no supera su media (8981 <= 64362.95)
2026-10-05 06:03:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6600 <= 4.7000) | No hay cruce alcista de VWAP (cierre anterior=4.7000, VWAP anterior=4.7493, cierre=4.6600, VWAP=4.7491) | El cierre no supera EMA50 (4.6600 <= 4.6919) | El volumen no supera su media (15738 <= 64384.25)
2026-10-05 06:04:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6200 <= 4.6600) | No hay cruce alcista de VWAP (cierre anterior=4.6600, VWAP anterior=4.7491, cierre=4.6200, VWAP=4.7488) | El cierre no supera EMA50 (4.6200 <= 4.6891) | El volumen no supera su media (15060 <= 64326.03)
2026-10-05 06:05:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6200, VWAP anterior=4.7488, cierre=4.6400, VWAP=4.7487) | El cierre no supera EMA50 (4.6400 <= 4.6872) | El volumen no supera su media (9378 <= 64360.08)
2026-10-05 06:06:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5900 <= 4.6400) | No hay cruce alcista de VWAP (cierre anterior=4.6400, VWAP anterior=4.7487, cierre=4.5900, VWAP=4.7483) | El cierre no supera EMA50 (4.5900 <= 4.6833) | El volumen no supera su media (22168 <= 64465.85)
2026-10-05 06:07:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5900, VWAP anterior=4.7483, cierre=4.6000, VWAP=4.7481) | El cierre no supera EMA50 (4.6000 <= 4.6801) | El volumen no supera su media (9724 <= 64435.38)
2026-10-05 06:08:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5900 <= 4.6000) | No hay cruce alcista de VWAP (cierre anterior=4.6000, VWAP anterior=4.7481, cierre=4.5900, VWAP=4.7479) | El cierre no supera EMA50 (4.5900 <= 4.6765) | El volumen no supera su media (9006 <= 64389.63)
2026-10-05 06:09:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5900, VWAP anterior=4.7479, cierre=4.6382, VWAP=4.7477) | El cierre no supera EMA50 (4.6382 <= 4.6750) | El volumen no supera su media (8668 <= 64417.86)
2026-10-05 06:10:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6000 <= 4.6382) | No hay cruce alcista de VWAP (cierre anterior=4.6382, VWAP anterior=4.7477, cierre=4.6000, VWAP=4.7476) | El cierre no supera EMA50 (4.6000 <= 4.6721) | El volumen no supera su media (7320 <= 64381.55)
2026-10-05 06:11:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5803 <= 4.6000) | No hay cruce alcista de VWAP (cierre anterior=4.6000, VWAP anterior=4.7476, cierre=4.5803, VWAP=4.7475) | El cierre no supera EMA50 (4.5803 <= 4.6685) | El volumen no supera su media (5655 <= 64192.09)
2026-10-05 06:12:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5300 <= 4.5803) | No hay cruce alcista de VWAP (cierre anterior=4.5803, VWAP anterior=4.7475, cierre=4.5300, VWAP=4.7471) | El cierre no supera EMA50 (4.5300 <= 4.6631) | El volumen no supera su media (12264 <= 63954.05)
2026-10-05 06:13:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5300, VWAP anterior=4.7471, cierre=4.5543, VWAP=4.7466) | El cierre no supera EMA50 (4.5543 <= 4.6588) | El volumen no supera su media (19576 <= 63813.44)
2026-10-05 06:14:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5005 <= 4.5543) | No hay cruce alcista de VWAP (cierre anterior=4.5543, VWAP anterior=4.7466, cierre=4.5005, VWAP=4.7461) | El cierre no supera EMA50 (4.5005 <= 4.6526) | El volumen no supera su media (18122 <= 63813.93)
2026-10-05 06:15:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5005, VWAP anterior=4.7461, cierre=4.5400, VWAP=4.7454) | El cierre no supera EMA50 (4.5400 <= 4.6482) | El volumen no supera su media (23111 <= 63808.03)
2026-10-05 06:16:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5400, VWAP anterior=4.7454, cierre=4.5725, VWAP=4.7452) | El cierre no supera EMA50 (4.5725 <= 4.6452) | El volumen no supera su media (9511 <= 63721.68)
2026-10-05 06:17:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5604 <= 4.5725) | No hay cruce alcista de VWAP (cierre anterior=4.5725, VWAP anterior=4.7452, cierre=4.5604, VWAP=4.7448) | El cierre no supera EMA50 (4.5604 <= 4.6419) | El volumen no supera su media (13132 <= 63774.98)
2026-10-05 06:18:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5506 <= 4.5604) | No hay cruce alcista de VWAP (cierre anterior=4.5604, VWAP anterior=4.7448, cierre=4.5506, VWAP=4.7446) | El cierre no supera EMA50 (4.5506 <= 4.6383) | El volumen no supera su media (9977 <= 63799.13)
2026-10-05 06:19:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5300 <= 4.5506) | No hay cruce alcista de VWAP (cierre anterior=4.5506, VWAP anterior=4.7446, cierre=4.5300, VWAP=4.7442) | El cierre no supera EMA50 (4.5300 <= 4.6341) | El volumen no supera su media (14915 <= 63912.56)
2026-10-05 06:20:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.4499 <= 4.5300) | No hay cruce alcista de VWAP (cierre anterior=4.5300, VWAP anterior=4.7442, cierre=4.4499, VWAP=4.7434) | El cierre no supera EMA50 (4.4499 <= 4.6268) | El volumen no supera su media (20882 <= 64067.82)
2026-10-05 06:21:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.4499, VWAP anterior=4.7434, cierre=4.4700, VWAP=4.7429) | El cierre no supera EMA50 (4.4700 <= 4.6207) | El volumen no supera su media (13746 <= 64185.76)
2026-10-05 06:22:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.4700, VWAP anterior=4.7429, cierre=4.4900, VWAP=4.7426) | El cierre no supera EMA50 (4.4900 <= 4.6156) | El volumen no supera su media (9716 <= 64247.00)
2026-10-05 06:23:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.4900 <= 4.4900) | No hay cruce alcista de VWAP (cierre anterior=4.4900, VWAP anterior=4.7426, cierre=4.4900, VWAP=4.7422) | El cierre no supera EMA50 (4.4900 <= 4.6106) | El volumen no supera su media (12451 <= 64273.67)
2026-10-05 06:24:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.4899 <= 4.4900) | No hay cruce alcista de VWAP (cierre anterior=4.4900, VWAP anterior=4.7422, cierre=4.4899, VWAP=4.7418) | El cierre no supera EMA50 (4.4899 <= 4.6059) | El volumen no supera su media (12205 <= 64346.84)
2026-10-05 06:25:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.4800 <= 4.4899) | No hay cruce alcista de VWAP (cierre anterior=4.4899, VWAP anterior=4.7418, cierre=4.4800, VWAP=4.7415) | El cierre no supera EMA50 (4.4800 <= 4.6010) | El volumen no supera su media (6341 <= 64321.45)
2026-10-05 06:26:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.4800, VWAP anterior=4.7415, cierre=4.5200, VWAP=4.7409) | El cierre no supera EMA50 (4.5200 <= 4.5978) | El volumen no supera su media (19173 <= 64212.72)
2026-10-05 06:27:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5200, VWAP anterior=4.7409, cierre=4.5897, VWAP=4.7403) | El cierre no supera EMA50 (4.5897 <= 4.5975) | El volumen no supera su media (28232 <= 64138.79)
2026-10-05 06:28:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5897, VWAP anterior=4.7403, cierre=4.6300, VWAP=4.7397) | El volumen no supera su media (36220 <= 63907.69)
2026-10-05 06:29:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.6000 <= 4.6300) | No hay cruce alcista de VWAP (cierre anterior=4.6300, VWAP anterior=4.7397, cierre=4.6000, VWAP=4.7395) | El volumen no supera su media (14707 <= 63136.60)
2026-10-05 06:30:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.6000, VWAP anterior=4.7395, cierre=4.6019, VWAP=4.7391) | El volumen no supera su media (20188 <= 62781.35)
2026-10-05 06:31:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5897 <= 4.6019) | No hay cruce alcista de VWAP (cierre anterior=4.6019, VWAP anterior=4.7391, cierre=4.5897, VWAP=4.7389) | El cierre no supera EMA50 (4.5897 <= 4.5986) | El volumen no supera su media (12861 <= 62033.27)
2026-10-05 06:32:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5700 <= 4.5897) | No hay cruce alcista de VWAP (cierre anterior=4.5897, VWAP anterior=4.7389, cierre=4.5700, VWAP=4.7387) | El cierre no supera EMA50 (4.5700 <= 4.5974) | El volumen no supera su media (9513 <= 59955.05)
2026-10-05 06:33:00-04:00 | SIN ENTRADA | El cierre no supera al anterior (4.5586 <= 4.5700) | No hay cruce alcista de VWAP (cierre anterior=4.5700, VWAP anterior=4.7387, cierre=4.5586, VWAP=4.7385) | El cierre no supera EMA50 (4.5586 <= 4.5959) | El volumen no supera su media (8579 <= 57934.96)
2026-10-05 06:34:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5586, VWAP anterior=4.7385, cierre=4.5800, VWAP=4.7383) | El cierre no supera EMA50 (4.5800 <= 4.5953) | El volumen no supera su media (9451 <= 56637.31)
2026-10-05 06:35:00-04:00 | SIN ENTRADA | No hay cruce alcista de VWAP (cierre anterior=4.5800, VWAP anterior=4.7383, cierre=4.6600, VWAP=4.7377) | El volumen no supera su media (42032 <= 55983.80)

In [ ]:
import numpy as np
import pandas as pd
from datetime import time
from backtesting import Backtest, Strategy


class ORB(Strategy):
    valor_R = 2.0
    objetivo_R = 2.0
    comision_fija = 0.001
    debug = True

    def init(self):
        if self.valor_R <= 0 or self.objetivo_R <= 0:
            raise ValueError("valor_R y objetivo_R deben ser positivos")

        index = self.data.index

        if not isinstance(index, pd.DatetimeIndex) or index.tz is None:
            raise ValueError("El índice debe tener zona horaria")

        self._horas = index.tz_convert("America/New_York")

        if not index.is_monotonic_increasing or index.has_duplicates:
            raise ValueError("El índice debe estar ordenado y sin duplicados")

        self._dia = None
        self._operado = False
        self._reportados = 0
        self.logs = []

    def _log(self, evento, mensaje, timestamp=None):
        timestamp = (
            self.data.index[-1] if timestamp is None else timestamp
        )
        texto = f"{timestamp} | {evento} | {mensaje}"
        self.logs.append(texto)

        if self.debug:
            print(texto)

    def report_closed_trades(self):
        for trade in self.closed_trades[self._reportados:]:
            self._log(
                "CIERRE",
                f"entrada={trade.entry_price:.4f} | "
                f"salida={trade.exit_price:.4f} | "
                f"acciones={trade.size} | P/L={trade.pl:.4f}",
                timestamp=trade.exit_time,
            )

        self._reportados = len(self.closed_trades)

    def next(self):
        self.report_closed_trades()

        ahora = self._horas[len(self.data) - 1]
        hora = ahora.time()

        if ahora.date() != self._dia:
            self._dia = ahora.date()
            self._operado = False

        # Con datos de 1 minuto y trade_on_close=True,
        # el cierre solicitado aquí se procesa en la barra 15:59.
        if hora >= time(15, 58):
            for order in list(self.orders):
                if not order.is_contingent:
                    order.cancel()

            if self.position:
                self.position.close()
                self._log("SALIDA", "Cierre por fin de sesión")

            return

        if hora < time(9, 45):
            return

        if self._operado or self.position or self.orders:
            return

        # Solo consulta barras ya disponibles: no usa precios futuros.
        horas = self._horas[:len(self.data)]
        apertura = (
            (horas.date == ahora.date())
            & (horas.time >= time(9, 30))
            & (horas.time < time(9, 45))
        )

        # Exige las 15 barras iniciales completas.
        esperadas = pd.date_range(
            ahora.normalize() + pd.Timedelta(hours=9, minutes=30),
            periods=15,
            freq="min",
        )

        if not horas[apertura].equals(esperadas):
            return

        maximo = float(np.max(np.asarray(self.data.High)[apertura]))
        minimo = float(np.min(np.asarray(self.data.Low)[apertura]))
        cierre = float(self.data.Close[-1])
        anterior = float(self.data.Close[-2])

        if not np.isfinite([maximo, minimo, cierre, anterior]).all():
            return

        if minimo <= 0 or maximo <= minimo:
            return

        # Primera ruptura confirmada al cierre de una vela.
        if not (anterior <= maximo < cierre):
            return

        # Consume el intento aunque no alcance el capital.
        self._operado = True

        riesgo_accion = cierre - minimo
        size_riesgo = int(self.valor_R / riesgo_accion)
        size_capital = max(
            0,
            int((self.equity - 2 * self.comision_fija) / cierre),
        )
        size = min(size_riesgo, size_capital)

        if size < 1:
            self._log("SIN ENTRADA", "Riesgo o capital insuficiente")
            return

        objetivo = cierre + self.objetivo_R * riesgo_accion

        self.buy(
            size=size,
            sl=minimo,
            tp=objetivo,
            tag="ORB",
        )

        self._log(
            "ENTRADA",
            f"rango={minimo:.4f}–{maximo:.4f} | "
            f"referencia={cierre:.4f} | "
            f"SL={minimo:.4f} | TP={objetivo:.4f} | "
            f"acciones={size} | riesgo nominal={size * riesgo_accion:.2f}",
        )

In [ ]:
# Solo sesión regular. Conserva la zona horaria del índice.
horas_ny = data.index.tz_convert("America/New_York")

data_orb = data.loc[
    (horas_ny.time >= time(9, 30))
    & (horas_ny.time < time(16, 0))
].copy()

bt_orb = Backtest(
    data_orb,
    ORB,
    cash=500,
    commission=(0.001, 0),
    trade_on_close=True,
    exclusive_orders=True,
    finalize_trades=True,
)

stats_orb = bt_orb.run(
    valor_R=2,
    objetivo_R=2,
    comision_fija=0.001,
    debug=True,
)

stats_orb["_strategy"].report_closed_trades()

display(stats_orb)
display(stats_orb["_trades"])
bt_orb.plot()

2026-10-05 09:55:00-04:00 | ENTRADA | rango=4.8900–5.4294 | referencia=5.5500 | SL=4.8900 | TP=6.8700 | acciones=3 | riesgo nominal=1.98
2026-10-05 11:33:00-04:00 | CIERRE | entrada=5.5500 | salida=4.8900 | acciones=3 | P/L=-1.9820
2026-10-09 10:17:00-04:00 | ENTRADA | rango=5.4000–6.2400 | referencia=6.4805 | SL=5.4000 | TP=8.6415 | acciones=1 | riesgo nominal=1.08
2026-10-09 13:50:00-04:00 | CIERRE | entrada=6.4805 | salida=5.4000 | acciones=1 | P/L=-1.0825

Start                     2026-10-05 09:30...
End                       2026-10-09 15:59...
Duration                      4 days 06:29:00
Exposure Time [%]                    40.33505
Equity Final [$]                     496.9355
Equity Peak [$]                      500.2987
Commissions [$]                         0.004
Return [%]                            -0.6129
Buy & Hold Return [%]                11.56778
Return (Ann.) [%]                    -42.2096
Volatility (Ann.) [%]                      --
CAGR [%]                            -40.89546
Sharpe Ratio                               --
Sortino Ratio                       -12.23286
Calmar Ratio                        -62.78962
Alpha [%]                             -0.6752
Beta                                  0.00539
Max. Drawdown [%]                    -0.67224
Avg. Drawdown [%]                    -0.34808
Max. Drawdown Duration        4 days 06:01:00
Avg. Drawdown Duration        2 days 03:02:00
# Trades                                    2
Win Rate [%]                              0.0
Best Trade [%]                       -11.9039
Worst Trade [%]                     -16.70396
Avg. Trade [%]                      -14.33755
Max. Trade Duration           0 days 03:33:00
Avg. Trade Duration           0 days 02:36:00
Profit Factor                             0.0
Expectancy [%]                      -14.30393
SQN                                  -3.40689
Kelly Criterion                            --
_strategy                 ORB(valor_R=2,ob...
_equity_curve                             ...
_trades                      Size  EntryBa...
dtype: object

,Size,EntryBar,ExitBar,EntryPrice,ExitPrice,SL,TP,PnL,Commission,ReturnPct,EntryTime,ExitTime,Duration,Tag
0,3,25,123,5.5500,4.89,4.89,6.8700,-1.9820,0.002,-0.119039,2026-10-05 09:55:00-04:00,2026-10-05 11:33:00-04:00,0 days 01:38:00,ORB
1,1,433,646,6.4805,5.40,5.40,8.6415,-1.0825,0.002,-0.167040,2026-10-09 10:17:00-04:00,2026-10-09 13:50:00-04:00,0 days 03:33:00,ORB

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

GridPlot(id='p2136', ...)

In [ ]:
stats._equity_curve.to_csv("equity.csv",sep=";")

In [ ]:
path_salida = os.path.join(data_dir,"output","VwapCross","results.parquet")
print(path_salida)
df = pl.read_parquet(path_salida)

E:\smallcaps_data\output\VwapCross\results.parquet

In [ ]:
df.filter(pl.col("Return [%]")<0)['Return [%]'].mean()

-0.8046699447204283