In [46]:
import yaml
import os
import polars as pl
from datetime import datetime ,date

with open("../config/config.yaml", "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

data_dir = config["data_dir"]
print(data_dir  )
if os.path.exists(data_dir) and os.path.isdir(data_dir):
    list_of_files = os.listdir(data_dir)
else:
    list_of_files = []
print(list_of_files)

E:\smallcaps_data
['AIXI.parquet', 'APUS.parquet', 'BAOS.parquet', 'BEAT.parquet', 'BIAF.parquet', 'CAN.parquet', 'CDTG.parquet', 'CHAI.parquet', 'CHPT.parquet', 'CISS.parquet', 'COOT.parquet', 'CYAB.parquet', 'FBGL.parquet', 'FLYE.parquet', 'GCDT.parquet', 'GIPR.parquet', 'GRI.parquet', 'GRML.parquet', 'IMCC.parquet', 'IMRN.parquet', 'LIDR.parquet', 'logs', 'MEDS.parquet', 'NCPL.parquet', 'NCRA.parquet', 'NEOV.parquet', 'OFAL.parquet', 'OLB.parquet', 'OLOX.parquet', 'output', 'PDSB.parquet', 'PFSA.parquet', 'SBFM.parquet', 'SDEV.parquet', 'SKYQ.parquet', 'SOAR.parquet', 'SPHL.parquet', 'STAK.parquet', 'TNMG.parquet', 'TOPP.parquet', 'TRUG.parquet', 'USDE.parquet', 'VEEA.parquet', 'VRA.parquet', 'VRME.parquet', 'XHLD.parquet', 'XPON.parquet', 'XTNT.parquet', '_catalog.parquet']

In [47]:
# list_of_files = [f for f in list_of_files if f.endswith(".parquet")]
list_of_tickers = [f for f in list_of_files if not f.startswith("_catalog") and f.endswith(".parquet")]
catalog = [f for f in list_of_files if f.startswith("_catalog") and f.endswith(".parquet")][0]
# parquet_path = os.path.join(data_dir, f"{ticker}.parquet")
catalog_path = os.path.join(data_dir, f"{catalog}")

df_catalog = pl.read_parquet(catalog_path)['ticker','end'].sort('ticker')
df_catalog = df_catalog.with_columns(
    pl.col('end').dt.date().alias('date')
)
df_catalog

shape: (105, 3)
┌────────┬─────────────────────────┬────────────┐
│ ticker ┆ end                     ┆ date       │
│ ---    ┆ ---                     ┆ ---        │
│ str    ┆ datetime[μs, UTC]       ┆ date       │
╞════════╪═════════════════════════╪════════════╡
│ AIXI   ┆ 2026-08-07 23:59:00 UTC ┆ 2026-08-07 │
│ AIXI   ┆ 2026-08-28 23:59:00 UTC ┆ 2026-08-28 │
│ APUS   ┆ 2026-09-04 20:32:00 UTC ┆ 2026-09-04 │
│ APUS   ┆ 2026-09-24 23:59:00 UTC ┆ 2026-09-24 │
│ APUS   ┆ 2026-10-07 23:59:00 UTC ┆ 2026-10-07 │
│ …      ┆ …                       ┆ …          │
│ XHLD   ┆ 2026-10-06 23:59:00 UTC ┆ 2026-10-06 │
│ XPON   ┆ 2026-08-04 20:05:00 UTC ┆ 2026-08-04 │
│ XPON   ┆ 2026-08-24 23:59:00 UTC ┆ 2026-08-24 │
│ XTNT   ┆ 2026-08-07 23:25:00 UTC ┆ 2026-08-07 │
│ XTNT   ┆ 2026-08-28 23:59:00 UTC ┆ 2026-08-28 │
└────────┴─────────────────────────┴────────────┘

In [48]:
df_backtest_runs = (
    df_catalog
    .select("ticker", "date")
    .unique()
    .sort(["ticker", "date"])
)
df_backtest_runs

shape: (104, 2)
┌────────┬────────────┐
│ ticker ┆ date       │
│ ---    ┆ ---        │
│ str    ┆ date       │
╞════════╪════════════╡
│ AIXI   ┆ 2026-08-07 │
│ AIXI   ┆ 2026-08-28 │
│ APUS   ┆ 2026-09-04 │
│ APUS   ┆ 2026-09-24 │
│ APUS   ┆ 2026-10-07 │
│ …      ┆ …          │
│ XHLD   ┆ 2026-10-06 │
│ XPON   ┆ 2026-08-04 │
│ XPON   ┆ 2026-08-24 │
│ XTNT   ┆ 2026-08-07 │
│ XTNT   ┆ 2026-08-28 │
└────────┴────────────┘

In [49]:
tickers_days = {
    row["ticker"]: row["days"]
    for row in (
        df_catalog
        .select(
            "ticker",
            pl.col("end").dt.strftime("%Y-%m-%d").alias("date"),
        )
        .group_by("ticker")
        .agg(
            pl.col("date")
            .unique()
            .sort(descending=True)
            .alias("days")
        )
        .sort("ticker")
        .to_dicts()
    )
}

tickers_days

{'AIXI': ['2026-08-28', '2026-08-07'],
 'APUS': ['2026-10-07', '2026-09-24', '2026-09-04'],
 'BAOS': ['2026-09-04', '2026-08-14'],
 'BEAT': ['2026-10-05', '2026-09-15'],
 'BIAF': ['2026-09-04', '2026-08-14'],
 'CAN': ['2026-08-21', '2026-07-31'],
 'CDTG': ['2026-09-04', '2026-08-14'],
 'CHAI': ['2026-08-28', '2026-08-07'],
 'CHPT': ['2026-09-03', '2026-08-14'],
 'CISS': ['2026-08-28', '2026-08-07'],
 'COOT': ['2026-08-31', '2026-08-11'],
 'CYAB': ['2026-08-28', '2026-08-07'],
 'FBGL': ['2026-09-22', '2026-09-02'],
 'FLYE': ['2026-10-08', '2026-09-18', '2026-09-01', '2026-08-12'],
 'GCDT': ['2026-09-23', '2026-09-03'],
 'GIPR': ['2026-08-25', '2026-08-24', '2026-08-04'],
 'GRI': ['2026-09-04', '2026-08-14'],
 'GRML': ['2026-09-25', '2026-09-04'],
 'IMCC': ['2026-09-22', '2026-09-02'],
 'IMRN': ['2026-09-04', '2026-08-14'],
 'LIDR': ['2026-09-01', '2026-08-12'],
 'MEDS': ['2026-10-08', '2026-09-18'],
 'NCPL': ['2026-09-21', '2026-09-01'],
 'NCRA': ['2026-08-31', '2026-08-11'],
 'NEOV': ['2026-08-31', '2026-08-11'],
 'OFAL': ['2026-10-09', '2026-10-08', '2026-09-18'],
 'OLB': ['2026-10-09', '2026-10-08', '2026-09-18', '2026-09-16'],
 'OLOX': ['2026-10-06', '2026-09-16'],
 'PDSB': ['2026-09-15', '2026-08-26'],
 'PFSA': ['2026-09-24', '2026-09-22', '2026-09-02'],
 'SBFM': ['2026-10-07', '2026-09-17'],
 'SDEV': ['2026-10-06', '2026-09-16'],
 'SKYQ': ['2026-09-24', '2026-09-04'],
 'SOAR': ['2026-09-14', '2026-08-26', '2026-08-06'],
 'SPHL': ['2026-09-24', '2026-09-04'],
 'STAK': ['2026-09-24', '2026-09-04'],
 'TNMG': ['2026-09-18'],
 'TOPP': ['2026-10-07', '2026-09-17'],
 'TRUG': ['2026-09-18', '2026-09-17', '2026-06-05'],
 'USDE': ['2026-09-18', '2026-08-28'],
 'VEEA': ['2026-10-09',
  '2026-10-08',
  '2026-09-18',
  '2026-09-15',
  '2026-08-25'],
 'VRA': ['2026-09-14', '2026-08-25'],
 'VRME': ['2026-09-21', '2026-09-01'],
 'XHLD': ['2026-10-06', '2026-09-16'],
 'XPON': ['2026-08-24', '2026-08-04'],
 'XTNT': ['2026-08-28', '2026-08-07']}

In [50]:

columns = ["datetime", "ticker", "open", "high", "low", "close", "volume"]
frames = []

for ticker, days in tickers_days.items():
    parquet_path = os.path.join(data_dir, f"{ticker}.parquet")

    if not os.path.isfile(parquet_path):
        raise FileNotFoundError(f"No existe el paquete Parquet para {ticker}: {parquet_path}")

    requested_days = [date.fromisoformat(day) for day in days]

    ticker_df = (
        pl.read_parquet(parquet_path)
        .filter(pl.col("datetime").dt.date().is_in(requested_days))
        .with_columns(pl.lit(ticker).alias("ticker"))
        .select(columns)
    )

    frames.append(ticker_df)

df = pl.concat(frames).sort(["ticker", "datetime"])
df

shape: (55_781, 7)
┌─────────────────────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ datetime                ┆ ticker ┆ open   ┆ high   ┆ low    ┆ close  ┆ volume │
│ ---                     ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs, UTC]       ┆ str    ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 2026-08-07 08:00:00 UTC ┆ AIXI   ┆ 1.08   ┆ 1.134  ┆ 1.01   ┆ 1.01   ┆ 5617   │
│ 2026-08-07 08:01:00 UTC ┆ AIXI   ┆ 1.07   ┆ 1.07   ┆ 1.07   ┆ 1.07   ┆ 753    │
│ 2026-08-07 08:02:00 UTC ┆ AIXI   ┆ 1.05   ┆ 1.05   ┆ 1.05   ┆ 1.05   ┆ 142    │
│ 2026-08-07 08:04:00 UTC ┆ AIXI   ┆ 1.03   ┆ 1.03   ┆ 1.03   ┆ 1.03   ┆ 138    │
│ 2026-08-07 08:06:00 UTC ┆ AIXI   ┆ 1.0207 ┆ 1.0207 ┆ 1.0207 ┆ 1.0207 ┆ 974    │
│ …                       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2026-08-28 23:48:00 UTC ┆ XTNT   ┆ 0.371  ┆ 0.371  ┆ 0.3666 ┆ 0.3666 ┆ 3638   │
│ 2026-08-28 23:49:00 UTC ┆ XTNT   ┆ 0.3709 ┆ 0.371  ┆ 0.3709 ┆ 0.3709 ┆ 5540   │
│ 2026-08-28 23:57:00 UTC ┆ XTNT   ┆ 0.3655 ┆ 0.3699 ┆ 0.3655 ┆ 0.3699 ┆ 703    │
│ 2026-08-28 23:58:00 UTC ┆ XTNT   ┆ 0.3699 ┆ 0.3699 ┆ 0.3643 ┆ 0.3643 ┆ 4101   │
│ 2026-08-28 23:59:00 UTC ┆ XTNT   ┆ 0.3651 ┆ 0.3651 ┆ 0.3651 ┆ 0.3651 ┆ 1128   │
└─────────────────────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [51]:
GROUPS = ["ticker", "trading_day"]


def daily_vwap():
    return [
        (
            (pl.col("price") * pl.col("volume")).cum_sum().over(GROUPS)
            / pl.col("volume").cum_sum().over(GROUPS)
        ).alias("vwap_daily")
    ]


def atr(period=14):
    previous_close = pl.col("close").shift(1).over(GROUPS)

    true_range = pl.max_horizontal(
        pl.col("high") - pl.col("low"),
        (pl.col("high") - previous_close).abs(),
        (pl.col("low") - previous_close).abs(),
    )

    return [
        true_range
        .rolling_mean(window_size=period, min_samples=period)
        .over(GROUPS)
        .alias(f"atr_{period}")
    ]


def bollinger_bands(period=20, std_dev=2.0):
    middle = pl.col("close").rolling_mean(period, min_samples=period).over(GROUPS)
    deviation = (
        pl.col("close")
        .rolling_std(period, min_samples=period, ddof=0)
        .over(GROUPS)
    )

    return [
        middle.alias(f"bb_middle_{period}"),
        (middle + deviation * std_dev).alias(f"bb_upper_{period}"),
        (middle - deviation * std_dev).alias(f"bb_lower_{period}"),
    ]


def rsi(period=14):
    change = pl.col("close").diff().over(GROUPS)
    gain = pl.when(change > 0).then(change).otherwise(0.0)
    loss = pl.when(change < 0).then(-change).otherwise(0.0)

    average_gain = (
        gain.ewm_mean(alpha=1 / period, adjust=False, min_samples=period)
        .over(GROUPS)
    )
    average_loss = (
        loss.ewm_mean(alpha=1 / period, adjust=False, min_samples=period)
        .over(GROUPS)
    )

    return [
        pl.when(average_loss == 0)
        .then(100.0)
        .when(average_gain == 0)
        .then(0.0)
        .otherwise(100.0 - (100.0 / (1.0 + average_gain / average_loss)))
        .alias(f"rsi_{period}")
    ]


def donchian_channels(period=20):
    upper = pl.col("high").rolling_max(period, min_samples=period).over(GROUPS)
    lower = pl.col("low").rolling_min(period, min_samples=period).over(GROUPS)

    return [
        upper.alias(f"donchian_upper_{period}"),
        lower.alias(f"donchian_lower_{period}"),
        ((upper + lower) / 2).alias(f"donchian_middle_{period}"),
    ]


def momentum(period=10):
    return [
        (
            pl.col("close")
            - pl.col("close").shift(period).over(GROUPS)
        ).alias(f"momentum_{period}")
    ]


def add_indicators(frame, indicator_functions):
    expressions = [
        expression
        for indicator_function in indicator_functions
        for expression in indicator_function()
    ]
    return frame.with_columns(expressions)


df_to_plot = (
    df
    .with_columns(
        pl.col("datetime").dt.convert_time_zone("America/New_York").alias("datetime")
    )
    .sort(["ticker", "datetime"])
    .with_columns(
        pl.col("datetime").dt.date().alias("trading_day"),
        ((pl.col("high") + pl.col("low") + pl.col("close")) / 3).alias("price"),
    )
)

df_to_plot = add_indicators(
    df_to_plot,
    [
        daily_vwap,
        atr,
        bollinger_bands,
        rsi,
        donchian_channels,
        momentum,
    ],
)

df_to_plot

shape: (55_781, 19)
┌─────────────┬────────┬────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ datetime    ┆ ticker ┆ open   ┆ high   ┆ … ┆ donchian_up ┆ donchian_lo ┆ donchian_m ┆ momentum_1 │
│ ---         ┆ ---    ┆ ---    ┆ ---    ┆   ┆ per_20      ┆ wer_20      ┆ iddle_20   ┆ 0          │
│ datetime[μs ┆ str    ┆ f64    ┆ f64    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ , America/N ┆        ┆        ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
│ ew_York]    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
╞═════════════╪════════╪════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 2026-08-07  ┆ AIXI   ┆ 1.08   ┆ 1.134  ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│ 04:00:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ 2026-08-07  ┆ AIXI   ┆ 1.07   ┆ 1.07   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│ 04:01:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ 2026-08-07  ┆ AIXI   ┆ 1.05   ┆ 1.05   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│ 04:02:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ 2026-08-07  ┆ AIXI   ┆ 1.03   ┆ 1.03   ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│ 04:04:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ 2026-08-07  ┆ AIXI   ┆ 1.0207 ┆ 1.0207 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│ 04:06:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ …           ┆ …      ┆ …      ┆ …      ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ 2026-08-28  ┆ XTNT   ┆ 0.371  ┆ 0.371  ┆ … ┆ 0.3717      ┆ 0.364       ┆ 0.36785    ┆ 0.0019     │
│ 19:48:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ 2026-08-28  ┆ XTNT   ┆ 0.3709 ┆ 0.371  ┆ … ┆ 0.3717      ┆ 0.364       ┆ 0.36785    ┆ 0.0062     │
│ 19:49:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ 2026-08-28  ┆ XTNT   ┆ 0.3655 ┆ 0.3699 ┆ … ┆ 0.3717      ┆ 0.364       ┆ 0.36785    ┆ 0.0052     │
│ 19:57:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ 2026-08-28  ┆ XTNT   ┆ 0.3699 ┆ 0.3699 ┆ … ┆ 0.3717      ┆ 0.364       ┆ 0.36785    ┆ -0.0052    │
│ 19:58:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ 2026-08-28  ┆ XTNT   ┆ 0.3651 ┆ 0.3651 ┆ … ┆ 0.3717      ┆ 0.364       ┆ 0.36785    ┆ 0.0011     │
│ 19:59:00    ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ EDT         ┆        ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
└─────────────┴────────┴────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [52]:
# import plotly.graph_objects as go
# from plotly.subplots import make_subplots


# GROUPS = ["ticker", "trading_day"]

# plot_df = (
#     df_to_plot
#     .sort(["ticker", "datetime"])
#     .with_row_index("plot_x")
# )


# def add_segmented_line(fig, frame, column, name, row, color, dash="solid", width=1):
#     """Añade una línea sin conectar distintos tickers ni días."""
#     show_legend = True

#     for segment in frame.partition_by(GROUPS, maintain_order=True):
#         valid_segment = segment.drop_nulls(column)

#         if valid_segment.height == 0:
#             continue

#         fig.add_trace(
#             go.Scatter(
#                 x=valid_segment["plot_x"].to_list(),
#                 y=valid_segment[column].to_list(),
#                 mode="lines",
#                 name=name,
#                 legendgroup=name,
#                 showlegend=show_legend,
#                 line={"color": color, "dash": dash, "width": width},
#             ),
#             row=row,
#             col=1,
#         )

#         show_legend = False


# volume_colors = [
#     "red" if close > open_price
#     else "green" if close < open_price
#     else "gray"
#     for open_price, close in zip(
#         plot_df["open"].to_list(),
#         plot_df["close"].to_list(),
#     )
# ]

# fig = make_subplots(
#     rows=5,
#     cols=1,
#     shared_xaxes=True,
#     vertical_spacing=0.025,
#     row_heights=[0.50, 0.15, 0.12, 0.12, 0.11],
#     subplot_titles=(
#         "Precio, VWAP, Bollinger y Donchian",
#         "Volumen",
#         "ATR 14",
#         "RSI 14",
#         "Momentum 10",
#     ),
# )

# fig.add_trace(
#     go.Candlestick(
#         x=plot_df["plot_x"].to_list(),
#         open=plot_df["open"].to_list(),
#         high=plot_df["high"].to_list(),
#         low=plot_df["low"].to_list(),
#         close=plot_df["close"].to_list(),
#         name="Precio",
#     ),
#     row=1,
#     col=1,
# )

# # Precio
# add_segmented_line(fig, plot_df, "vwap_daily", "VWAP", 1, "orange", width=2)

# # Bandas de Bollinger
# add_segmented_line(fig, plot_df, "bb_upper_20", "BB superior", 1, "#7f7f7f", "dot")
# add_segmented_line(fig, plot_df, "bb_middle_20", "BB media", 1, "#7f7f7f")
# add_segmented_line(fig, plot_df, "bb_lower_20", "BB inferior", 1, "#7f7f7f", "dot")

# # Canales de Donchian
# add_segmented_line(
#     fig, plot_df, "donchian_upper_20", "Donchian superior", 1, "#9467bd", "dash"
# )
# add_segmented_line(
#     fig, plot_df, "donchian_middle_20", "Donchian medio", 1, "#9467bd", "dot"
# )
# add_segmented_line(
#     fig, plot_df, "donchian_lower_20", "Donchian inferior", 1, "#9467bd", "dash"
# )

# # Volumen: vela alcista rojo, vela bajista verde
# fig.add_trace(
#     go.Bar(
#         x=plot_df["plot_x"].to_list(),
#         y=plot_df["volume"].to_list(),
#         marker_color=volume_colors,
#         name="Volumen",
#     ),
#     row=2,
#     col=1,
# )

# # Indicadores inferiores
# add_segmented_line(fig, plot_df, "atr_14", "ATR 14", 3, "#1f77b4", width=2)
# add_segmented_line(fig, plot_df, "rsi_14", "RSI 14", 4, "#ff7f0e", width=2)
# add_segmented_line(fig, plot_df, "momentum_10", "Momentum 10", 5, "#2ca02c", width=2)

# fig.add_hline(y=70, row=4, col=1, line_dash="dot", line_color="red")
# fig.add_hline(y=30, row=4, col=1, line_dash="dot", line_color="green")
# fig.update_yaxes(range=[0, 100], row=4, col=1)

# # Una marca de eje por inicio de cada día y ticker.
# day_starts = (
#     plot_df
#     .group_by(GROUPS, maintain_order=True)
#     .agg(pl.col("plot_x").min().alias("plot_x"))
#     .sort("plot_x")
# )

# fig.update_xaxes(
#     tickmode="array",
#     tickvals=day_starts["plot_x"].to_list(),
#     ticktext=[
#         f"{row['ticker']}<br>{row['trading_day']}"
#         for row in day_starts.to_dicts()
#     ],
#     row=5,
#     col=1,
# )

# # Etiqueta centrada sobre cada tramo de ticker.
# ticker_ranges = (
#     plot_df
#     .group_by("ticker", maintain_order=True)
#     .agg(
#         pl.col("plot_x").min().alias("start"),
#         pl.col("plot_x").max().alias("end"),
#     )
# )

# for ticker_range in ticker_ranges.to_dicts():
#     fig.add_annotation(
#         x=(ticker_range["start"] + ticker_range["end"]) / 2,
#         y=1.03,
#         xref="x",
#         yref="paper",
#         text=f"<b>{ticker_range['ticker']}</b>",
#         showarrow=False,
#     )

# fig.update_layout(
#     title="Precio e indicadores técnicos",
#     xaxis_rangeslider_visible=False,
#     height=1_300,
#     barmode="overlay",
# )

# fig.show()

Conversion de data para backtesting

In [53]:
def get_data_to_backtesting(df,ticker,date):
    data = df_to_plot.filter(pl.col('ticker')==ticker).filter(pl.col('datetime').dt.date()==date)
    data.columns = [c[0].upper()+c[1:].lower() for c in df_to_plot.columns]
    data = data.to_pandas().set_index('Datetime')
    return data

In [54]:
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
import numpy as np
from backtesting.test import SMA, GOOG


class VwapCross(Strategy):


    max_bars = 5
    valor_R=2
    def bollinger_bands_indicator(self):
        return np.vstack(
            (
                self.data.Bb_upper_20,
                self.data.Bb_middle_20,
                self.data.Bb_lower_20,
            )
        )
    def donchian_channels_indicator(self):
            return np.vstack(
                (
                    self.data.Donchian_upper_20	,
                    self.data.Donchian_lower_20,
                    self.data.Donchian_middle_20,
                )
            )
    
    def vwap_indicator(self):
        return self.data.Vwap_daily
    def atr_indicator(self):
            return self.data.Atr_14
    def momentum_indicator(self):
            return self.data.Momentum_10
    def rsi_indicator(self):
         return self.data.Rsi_14
    def init(self):
        price = self.data.Close
        self.vwap = self.I(self.vwap_indicator)
        # self.atr = self.I(self.atr_indicator)
        self.momentum= self.I(self.momentum_indicator)
        self.rsi = self.I(self.rsi_indicator)

        # self.bb_upper, self.bb_middle, self.bb_lower = self.I(
        #     self.bollinger_bands_indicator,
        #     name=("BB superior", "BB media", "BB inferior"),
        #     overlay=True,
        # )
        # self.donchian_upper, self.donchian_middle, self.donchian_lower = self.I(
        #     self.donchian_channels_indicator,
        #     name=("donchian superior", "donchian media", "donchian inferior"),
        #     overlay=True,
        # )
        self.nbars=0
        # self.ma2 = self.I(SMA, price, 20)
        self.data_ant=None

    def next(self):
        # if crossover(self.data.Close, self.data.Vwap_daily) and not self.position.is_long:
        if self.data.Close[-1]> self.data.Vwap_daily[-1] and self.data.Close[-2]< self.data.Vwap_daily[-2] and not self.trades and not self.orders:
            recent_volumes = self.data.Volume[-4:-1]
            if len(recent_volumes) == 3 and (
                self.data.Volume[-1] * 30 >= sum(recent_volumes) * 11
            ):
                # sl= self.data.Low[-3:].min()
                # tp =self.data.Close+ (self.data.Close-sl)*2
                sl= self.data.Close[-1]-self.data.Atr_14[-1]*2
                sl2= self.data.Close[-1]-self.data.Atr_14[-1]*2
                sl3= self.data.Close[-1]-self.data.Atr_14[-1]*2
                tp =self.data.Close[-1]+self.data.Atr_14[-1]*2
                tp2 =self.data.Close[-1]+self.data.Atr_14[-1]*3
                tp3 =self.data.Close[-1]+self.data.Atr_14[-1]*6
                self.nbars=0
                if sl>0 and tp>0:
                    # print(self.data.Close[-1],sl,tp)

                    size = int(self.valor_R/(self.data.Close[-1]-sl))
                    size2=int (size/4)
                    size3=int (size/4)
                    size1 = size-size2-size3
                    # print(size)
                    # print(self.data.Close[-1],sl,tp,size,size1,size2,size3)
                    # self.buy(sl=sl,tp=tp,size=size1)
                    # self.buy(sl=sl2,tp=tp2,size=size2)
                    # self.buy(sl=sl3,tp=tp3,size=size3)
                    self.buy(sl=sl, tp=tp, size=size1, tag="salida 1")
                    self.buy(sl=sl2, size=size2, tag="salida 2")
                    self.buy(sl=sl3, size=size3, tag="salida 3")

        open_price = self.data.Open[-1]
        high_price = self.data.High[-1]
        low_price = self.data.Low[-1]
        close_price = self.data.Close[-1]
        previous_open = self.data.Open[-2]
        previous_close = self.data.Close[-2]
        
        body = abs(close_price - open_price)
        upper_wick = high_price - max(open_price, close_price)
        lower_wick = min(open_price, close_price) - low_price
        upper_wick_signal = (
            body > 0
            and upper_wick > body * 3
            and lower_wick < upper_wick*1.5
        )

        bearish_engulfing_signal = (
            previous_close > previous_open      # vela anterior alcista
            and close_price < open_price        # vela actual bajista
            and open_price >= previous_close    # abre por encima del cierre previo
            and close_price <= previous_open    # cierra por debajo de la apertura previa
            and body > abs(previous_close - previous_open)
        )

        salida_1_abierta = any(
            trade.tag == "salida 1" for trade in self.trades
        )

        if not salida_1_abierta:
            for trade in self.trades:
                if trade.tag == "salida 2" and upper_wick_signal:
                    trade.close()

                if trade.tag == "salida 3" and bearish_engulfing_signal:
                    trade.close()
                # elif crossover(self.data.Close, self.data.vwap_daily):
                    # self.sell()
                # if self.position.is_long:
                #     self.nbars+=1
                #     if self.nbars>=self.max_bars:
                        
                #         self.position.close()
                self.data_ant = self.data

In [55]:
from pathlib import Path
from datetime import timedelta
import math


def strategy_name(strategy):
    """Return the class name for a Backtesting.py strategy class or instance."""
    return strategy.__name__ if isinstance(strategy, type) else type(strategy).__name__


def build_backtest_output_dir(config, strategy, ticker, trading_date):
    """Build the output directory without creating it."""
    day = trading_date.date() if isinstance(trading_date, datetime) else trading_date
    return (
        Path(config["data_dir"])
        / "output"
        / strategy_name(strategy)
        / str(ticker)
        / day.strftime("%Y%m%d")
    )


def backtesting_stats_to_scalar_metrics(stats):
    """Keep only scalar Backtesting.py statistics suitable for Polars/Parquet."""
    metrics = {}
    for key, value in stats.items():
        if str(key).startswith("_"):
            continue

        if isinstance(value, np.generic):
            value = value.item()

        if isinstance(value, (datetime, date)):
            value = value.isoformat()
        elif isinstance(value, timedelta):
            value = value.total_seconds()
        elif isinstance(value, float) and not math.isfinite(value):
            value = None
        elif not isinstance(value, (str, int, float, bool, type(None))):
            continue

        metrics[str(key)] = value
    return metrics

In [56]:
def run_and_persist_backtest(ticker, trading_date):
    """Run and persist one ticker/date backtest using the current strategy settings."""
    day = trading_date.date() if isinstance(trading_date, datetime) else trading_date
    data = get_data_to_backtesting(df_to_plot, ticker, day)

    if data.empty:
        raise ValueError(f"No backtesting data available for {ticker} on {day:%Y-%m-%d}.")

    bt = Backtest(
        data,
        VwapCross,
        commission=(0.001, 0),
        cash=500,
        exclusive_orders=False,
    )
    stats = bt.run(valor_R=2)

    output_dir = build_backtest_output_dir(config, VwapCross, ticker, day)
    output_dir.mkdir(parents=True, exist_ok=True)

    result_row = {
        **backtesting_stats_to_scalar_metrics(stats),
        "strategy": strategy_name(VwapCross),
        "ticker": str(ticker),
        "date": day.isoformat(),
    }
    result = pl.DataFrame([result_row])
    result.write_parquet(output_dir / "stats.parquet")
    bt.plot(filename=str(output_dir / "backtest.html"), open_browser=False)
    return result

In [57]:
def run_and_persist_backtest_batch(df_runs):
    """Run, persist, and aggregate every ticker/date combination in df_runs."""
    results = []
    current_strategy = strategy_name(VwapCross)

    for run in df_runs.select("ticker", "date").iter_rows(named=True):
        ticker = str(run["ticker"])
        trading_date = run["date"]
        day = trading_date.date() if isinstance(trading_date, datetime) else trading_date

        try:
            result = run_and_persist_backtest(ticker, trading_date).with_columns(
                pl.lit("success").alias("status"),
                pl.lit(None, dtype=pl.Utf8).alias("error_message"),
            )
        except Exception as exc:
            result = pl.DataFrame(
                [
                    {
                        "strategy": current_strategy,
                        "ticker": ticker,
                        "date": day.isoformat(),
                        "status": "failed",
                        "error_message": str(exc),
                    }
                ]
            )

        results.append(result)

    if results:
        aggregated = pl.concat(results, how="diagonal_relaxed").sort(["ticker", "date"])
    else:
        aggregated = pl.DataFrame(
            schema={
                "strategy": pl.Utf8,
                "ticker": pl.Utf8,
                "date": pl.Utf8,
                "status": pl.Utf8,
                "error_message": pl.Utf8,
            }
        )

    output_dir = Path(config["data_dir"]) / "output" / current_strategy
    output_dir.mkdir(parents=True, exist_ok=True)
    aggregated.write_parquet(output_dir / "results.parquet")
    return aggregated

In [58]:
ticker = "VEEA"
trading_date = datetime.strptime("2026-10-09", "%Y-%m-%d")
backtest_result = run_and_persist_backtest(ticker, trading_date)
backtest_result

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

shape: (1, 35)
┌────────────┬────────────┬──────────┬────────────┬───┬───────────┬───────────┬────────┬───────────┐
│ Start      ┆ End        ┆ Duration ┆ Exposure   ┆ … ┆ Kelly     ┆ strategy  ┆ ticker ┆ date      │
│ ---        ┆ ---        ┆ ---      ┆ Time [%]   ┆   ┆ Criterion ┆ ---       ┆ ---    ┆ ---       │
│ str        ┆ str        ┆ f64      ┆ ---        ┆   ┆ ---       ┆ str       ┆ str    ┆ str       │
│            ┆            ┆          ┆ f64        ┆   ┆ f64       ┆           ┆        ┆           │
╞════════════╪════════════╪══════════╪════════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 2026-10-09 ┆ 2026-10-09 ┆ 57540.0  ┆ 19.30745   ┆ … ┆ 0.057842  ┆ VwapCross ┆ VEEA   ┆ 2026-10-0 │
│ T04:00:00- ┆ T19:59:00- ┆          ┆            ┆   ┆           ┆           ┆        ┆ 9         │
│ 04:00      ┆ 04:00      ┆          ┆            ┆   ┆           ┆           ┆        ┆           │
└────────────┴────────────┴──────────┴────────────┴───┴───────────┴───────────┴────────┴───────────┘

In [59]:
df_backtest_results = run_and_persist_backtest_batch(df_backtest_runs)
df_backtest_results

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

C:\Users\FLODEV\AppData\Local\Temp\ipykernel_36612\614548399.py:16: UserWarning:

Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning:

time=108: Broker canceled the order due to insufficient margin (equity=500.92, margin_available=65.52).

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning:

time=177: Broker canceled the order due to insufficient margin (equity=498.09, margin_available=129.93).

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

C:\Users\FLODEV\AppData\Local\Temp\ipykernel_36612\614548399.py:16: UserWarning:

Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

C:\Users\FLODEV\AppData\Local\Temp\ipykernel_36612\614548399.py:16: UserWarning:

Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

C:\Users\FLODEV\AppData\Local\Temp\ipykernel_36612\614548399.py:16: UserWarning:

Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

C:\Users\FLODEV\AppData\Local\Temp\ipykernel_36612\614548399.py:16: UserWarning:

Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

C:\Users\FLODEV\AppData\Local\Temp\ipykernel_36612\614548399.py:16: UserWarning:

Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

C:\Users\FLODEV\AppData\Local\Temp\ipykernel_36612\614548399.py:16: UserWarning:

Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

C:\Users\FLODEV\AppData\Local\Temp\ipykernel_36612\614548399.py:16: UserWarning:

Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

C:\Users\FLODEV\AppData\Local\Temp\ipykernel_36612\614548399.py:16: UserWarning:

Some trades remain open at the end of backtest. Use `Backtest(..., finalize_trades=True)` to close them and include them in stats.

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

d:\00_PROG\23_algo_trd\021_sm_framework\venv\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning:

no explicit representation of timezones available for np.datetime64

shape: (104, 37)
┌────────────┬────────────┬──────────┬────────────┬───┬────────┬────────────┬─────────┬────────────┐
│ Start      ┆ End        ┆ Duration ┆ Exposure   ┆ … ┆ ticker ┆ date       ┆ status  ┆ error_mess │
│ ---        ┆ ---        ┆ ---      ┆ Time [%]   ┆   ┆ ---    ┆ ---        ┆ ---     ┆ age        │
│ str        ┆ str        ┆ f64      ┆ ---        ┆   ┆ str    ┆ str        ┆ str     ┆ ---        │
│            ┆            ┆          ┆ f64        ┆   ┆        ┆            ┆         ┆ str        │
╞════════════╪════════════╪══════════╪════════════╪═══╪════════╪════════════╪═════════╪════════════╡
│ 2026-08-07 ┆ 2026-08-07 ┆ 57540.0  ┆ 4.528986   ┆ … ┆ AIXI   ┆ 2026-08-07 ┆ success ┆ null       │
│ T04:00:00- ┆ T19:59:00- ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 04:00      ┆ 04:00      ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 2026-08-28 ┆ 2026-08-28 ┆ 57540.0  ┆ 9.80663    ┆ … ┆ AIXI   ┆ 2026-08-28 ┆ success ┆ null       │
│ T04:00:00- ┆ T19:59:00- ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 04:00      ┆ 04:00      ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 2026-09-04 ┆ 2026-09-04 ┆ 25320.0  ┆ 0.0        ┆ … ┆ APUS   ┆ 2026-09-04 ┆ success ┆ null       │
│ T09:30:00- ┆ T16:32:00- ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 04:00      ┆ 04:00      ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 2026-09-24 ┆ 2026-09-24 ┆ 57540.0  ┆ 4.460432   ┆ … ┆ APUS   ┆ 2026-09-24 ┆ success ┆ null       │
│ T04:00:00- ┆ T19:59:00- ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 04:00      ┆ 04:00      ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ null       ┆ null       ┆ null     ┆ null       ┆ … ┆ APUS   ┆ 2026-10-07 ┆ failed  ┆ size must  │
│            ┆            ┆          ┆            ┆   ┆        ┆            ┆         ┆ be a       │
│            ┆            ┆          ┆            ┆   ┆        ┆            ┆         ┆ positive   │
│            ┆            ┆          ┆            ┆   ┆        ┆            ┆         ┆ fracti…    │
│ …          ┆ …          ┆ …        ┆ …          ┆ … ┆ …      ┆ …          ┆ …       ┆ …          │
│ 2026-10-06 ┆ 2026-10-06 ┆ 57540.0  ┆ 24.810127  ┆ … ┆ XHLD   ┆ 2026-10-06 ┆ success ┆ null       │
│ T04:00:00- ┆ T19:59:00- ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 04:00      ┆ 04:00      ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 2026-08-04 ┆ 2026-08-04 ┆ 31740.0  ┆ 3.571429   ┆ … ┆ XPON   ┆ 2026-08-04 ┆ success ┆ null       │
│ T07:16:00- ┆ T16:05:00- ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 04:00      ┆ 04:00      ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ null       ┆ null       ┆ null     ┆ null       ┆ … ┆ XPON   ┆ 2026-08-24 ┆ failed  ┆ size must  │
│            ┆            ┆          ┆            ┆   ┆        ┆            ┆         ┆ be a       │
│            ┆            ┆          ┆            ┆   ┆        ┆            ┆         ┆ positive   │
│            ┆            ┆          ┆            ┆   ┆        ┆            ┆         ┆ fracti…    │
│ 2026-08-07 ┆ 2026-08-07 ┆ 35400.0  ┆ 0.0        ┆ … ┆ XTNT   ┆ 2026-08-07 ┆ success ┆ null       │
│ T09:35:00- ┆ T19:25:00- ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 04:00      ┆ 04:00      ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 2026-08-28 ┆ 2026-08-28 ┆ 57540.0  ┆ 36.256684  ┆ … ┆ XTNT   ┆ 2026-08-28 ┆ success ┆ null       │
│ T04:00:00- ┆ T19:59:00- ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
│ 04:00      ┆ 04:00      ┆          ┆            ┆   ┆        ┆            ┆         ┆            │
└────────────┴────────────┴──────────┴────────────┴───┴────────┴────────────┴─────────┴────────────┘

In [60]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

kpi_columns = [
    "Return [%]",
    "Buy & Hold Return [%]",
    "Win Rate [%]",
    "Avg. Trade [%]",
    "Avg. Drawdown [%]",
    "Expectancy [%]",
]

missing_kpi_columns = [column for column in kpi_columns if column not in df_backtest_results.columns]
if missing_kpi_columns:
    raise ValueError(
        "Cannot plot KPI histograms because df_backtest_results is missing: "
        + ", ".join(missing_kpi_columns)
    )

successful_backtests = df_backtest_results.filter(pl.col("status") == "success")
if successful_backtests.height == 0:
    raise ValueError("Cannot plot KPI histograms because there are no successful backtest results.")

fig = make_subplots(
    rows=2,
    cols=3,
    subplot_titles=kpi_columns,
)

for index, kpi in enumerate(kpi_columns):
    row = index // 3 + 1
    col = index % 3 + 1
    values = successful_backtests.get_column(kpi).drop_nulls().to_list()
    fig.add_trace(
        go.Histogram(x=values, name=kpi, showlegend=False),
        row=row,
        col=col,
    )
    fig.update_xaxes(title_text=kpi, row=row, col=col)
    fig.update_yaxes(title_text="Count", row=row, col=col)

fig.update_layout(
    title="Backtest KPI distributions",
    height=700,
    width=1_300,
)
fig.show()